### ISSUE TITLE
Add more GraphQL docs

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#100]
The top level `Query` already has docs. We should also document the `Realm` type, and any future type to come.

**Comment by LukasKalbertodt** [comment]
I removed it from the sprint because this is a continuous effort and only makes sense if we have an API we are fairly sure we'll keep.

**Comment by LukasKalbertodt** [comment]
Since the issue was created, tons has changed. I don't really think having this issue open serves a purpose. As I said in my last comment, this is a continuous effort and is never really "done".
