### ISSUE TITLE
Reconsider description placement of series blocks

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#1007]
Series blocks have the option to have their description displayed. When this is used in a page with multiple blocks, the result can look a little awkward, since it's not necessarily obvious that the text belongs to the series below: 
<img width="1507" alt="Bildschirmfoto 2023-11-21 um 17 50 56" src="https://github.com/elan-ev/tobira/assets/94838646/2dbc34d1-c8a5-40fa-981e-1fd7671275bb">

Tobira uses this layout predominantly for series __pages__, where the series and its description are the only elements besides the page title, making things more obvious:
<img width="1507" alt="Bildschirmfoto 2023-11-21 um 17 57 30" src="https://github.com/elan-ev/tobira/assets/94838646/fda9fbd3-aa3d-4d40-8f80-4501b4914a3e">

One could argue that for consitency's sake it would be best to always have the description text inside the grey box, positioning the sorting/layout menu buttons below the text and dividing longer text into two columns, to make better use of the available space:
<img width="1507" alt="Bildschirmfoto 2023-11-21 um 18 05 40" src="https://github.com/elan-ev/tobira/assets/94838646/76da656a-4ee0-4a9a-9ac0-8503562459b6">

I think we should remove the layout option that results in the top-most screenshot to prevent such situations. Then series blocks inside non-series pages would always look like shown in the third screenshot.
But maybe we can consider keeping it internally for series pages, like shown in the second screenshot.

**Comment by oas777** [comment]
I would "argue that for consitency's sake it would be best to always have the description text inside the grey box".

**Comment by owi92** [comment]
> One could argue that for consitency's sake it would be best to always have the description text inside the grey box

Just so we're super clear about what I meant with that: Doing this for regular series blocks is not really up for debate (well it is if you want it to be, but what I'm saying is that this should definitely be changed to always have the description text inside the grey box - both of you seem to agree with that).

What I meant to ask is if we should also do this for series pages.
- A series **page** is not a series block, but it does contain one.
- Every series has their own series page.
- These can't have any other elements besides the title, description and videos of a single series.
- For a live example, see https://tobira.opencast.org/!s/Ga6l3dvtHB0.
- A series **block** on the other hand is an element that can be surrounded by other series blocks, videos, titles and texts. That's where a description that is separate from the box is problematic.

The proposed change for this would result in something like shown in the screenshot below.
For series pages, I slightly prefer what you can see in the link above. I think it's already well structured and doesn't really benefit from pulling the text inside the grey box. I wonder if that even needs to have a grey box at all.
But what we do with that ultimately remains your decision of course.
![Screenshot 2023-11-23 at 17-59-50 Getting Serious about Science Education • Tobira Videoportal](https://github.com/elan-ev/tobira/assets/94838646/a4515a30-18f8-46d1-a555-917ad1a60009)
