### ISSUE TITLE
Discuss different styling of `link` buttons again

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#1014]
This is specifically about the `manage` button on video pages. The color of that button was changed a while back to address the issue described in #660.
Unfortunately this has been the cause of confusion for a couple of times now, when people were wondering about the visual discrepancy between this button and the `download` and `share` buttons.
So this is clearly not the best solution. We need to find another way to relay the different behaviour of these buttons (the difference being that the `manage` button is a link that navigates to another page, while `download` and `share` both open a popup menu without changing routes).
<img width="948" alt="Bildschirmfoto 2023-11-22 um 15 48 08" src="https://github.com/elan-ev/tobira/assets/94838646/bd57de39-6a22-4002-9c6b-768bcd791286">

**Comment by LukasKalbertodt** [comment]
I'm probably also in favor of moving that button somewhere else and maybe even styling it differently, i.e. not a button but as the link it is. And yes maybe below the metadata table?

**Comment by dagraf** [comment]
I would argue against moving the "Manage" button to a totally different area. At the moment, I have everything with what I can do something on the same line. This is identically done on YouTube, see screenshot. Note: YouTube does not care if an identically styled buttons sends users to a different link or open a modal. Therefore, I would like to readdress the need to color the buttons differently. And if we end up with a "Yes, we want different colors", I would then suggest to have the styles of the link- and modal-button more different and maybe moving them apart a little.

<img width="823" alt="Bildschirmfoto 2023-12-06 um 15 38 57" src="https://github.com/elan-ev/tobira/assets/15246287/87f79493-4215-44d4-a55d-cba67abe9723">
