### ISSUE TITLE
Reorder the videos in the series view

### ISSUE THREAD

**Issue by kaspot** [elan-ev/tobira#1018]
There are two things to be considered: 
1. If I change the "view" of the videos via "Edit page content" I would expect that the view will be changed for all users
2. I would like to have the option to reorder the videos as wished and then "save" this order for all users (if I do this with the "Edit page content" option.

**Comment by LukasKalbertodt** [comment]
Pretty sure this is fixed. In case the second point means arbitrary ordering: I don't think we want to support that. That sounds like a job for playlists instead. Since I haven't gotten a reply since Feb, I will close.
