### ISSUE TITLE
Consent to Terms and Conditions on first use

### ISSUE THREAD

**Issue by ziegenberg** [elan-ev/tobira#1023]
It is common practice to require (authenticated and/or anonymous) users to agree to terms and conditions to comply with local laws and regulations when using a platform. Tobira should provide such a mechanism for universities and other organisations.

- For anonymous users, it should be stored in a cookie.
- For authenticated users, it should be stored in the database.
- The date and time of consent should be recorded.
- If the terms and conditions change, consent should be obtained again.
- This mechanism should support different documents a user should be notified about on first use: eg. accessibility declaration, GDPR Notices, ...

**Comment by oas777** [comment]
+1 Especially in case we try to track users with Matomo...

**Comment by dagraf** [comment]
+1

**Comment by LukasKalbertodt** [comment]
I thought a bit about this. Here are some thoughts/ideas. Let me know if this works for you.

The basic idea is that there are three configuration values (all "translated strings", i.e. you can specify them for different languages): `title`, `button-label` and `text`:

```toml
[general.initial-consent]
title.en = "Terms & Conditions"
button-label.en = "Agree"
text.en = """
By using this video portal, you agree to donate your (living) body for scientific experiments. 
You also agree to:
- [Our data retention policy](https://my-uni.de/datenkrake)
- [Accessibility declaration](https://www.reddit.com/r/accessibilityfails/top/?t=all)
"""
```

If those fields are configured, Tobira will show a popup with the given title (at the top), a button on the bottom right with the given label, and with the given text as main content. The `text` will be rendered as basic Markdown, allowing you to link other documents and write whatever. The arbitrary text is probably the most straight forward and flexible solution?

So yeah, would that work for all of you? In particular: is one button really enough? And the popup can actually not be closed apart from clicking the one "agree" button?

> For anonymous users, it should be stored in a cookie.

We will likely use local storage, but unimportant implementation detail :shrug: (except if we missed something and cookie is better in this case, please tell us then)

> If the terms and conditions change, consent should be obtained again.

When we store the "agreement" of a user (in DB or local storage), we would also attach the exact contents (well, a hash of it) of what the user agreed to. If that changes, the user is prompted again. Does that work for you? This means that if you fix a typo, or improve formatting, the users are prompted again. Or would you rather have a way to manually control "re-prompts" by, e.g. having a "version" configuration value that you have to manually increase to reprompt? I would probably argue for the first solution as the latter one adds more complexity and is also error prone as you might forget to increase the version.

---

<sup>While I fully understand that Tobira needs this, and I'm not arguing against it, I still feel the urge to state that I really despise these things for several reasons. Often, they are not even necessary, but the organization's lawyer just asks for it to be safe, sacrificing UX in the process. There is also some debate about how legally binding these things are anyway; it's common knowledge that no one reads these. And finally, I dislike the data collection practices that require these notices to begin with. The "collect everything first, think later" approach is a very bad one IMO. *Anyway*, this is just me shouting in the void, I know that you (three) are not deciding these things and there are legitimate uses for sure. With this statement out of the way, I will now shut up about it.</sup>

**Comment by oas777** [comment]
I think this is sufficient, no need for checking the version in case of changes to the TOS. I presume we agree the "button-label.en" is, mmh, at the bottom?

**Comment by ziegenberg** [comment]
A few notes:

Rendering plain text as Markdown is perfectly fine for us. It provides everything we need: Headings, paragraphs, ordered and unordered lists, links and basic formatting (bold, italics and underlined).

I only used the term "cookie" because it's a commonly known client-side data store; just use whatever location you think is more appropriate.

I'm not in favour of storing the text and title in the configuration but rather in the database to change it at runtime without redeploying/reconfiguring the application. The people changing the T&C text may not be the admins deploying Tobira.

Ideally, a small change (correcting a typo) SHOULD NOT prompt the user again. I suggest a checkbox labelled "This is a minor change" when the T&C text is edited, which updates the record for the current version in the database rather than creating a new version. By default, the checkbox SHOULD NOT be ticked.

We probably need two buttons, "Agree" and "Disagree", as the user MUST be able to decide. If he disagrees, he MUST NOT have access to Tobira.

**Comment by LukasKalbertodt** [comment]
>  If he disagrees, he MUST NOT have access to Tobira.

So... what should happen if they click "disagree"? The ETH and Bern also said that users cannot have access to Tobira unless they agree, but then why bother showing a disagree button? It would make the user think they have the option to disagree when in fact they have not.

---

Regarding storing in the DB and having a UI to change this text: this is significantly more work than just using the configuration. It's certainly doable, don't get me wrong, just speaking *relative* to the configuration solution it's waaay more work. And I don't think that's worth it ... we have tons of other things to do right now. How often do you expect the text to change? It shouldn't be that often, if only to prevent annoying users, right?

**Comment by oas777** [comment]
-1 for investing "waaay more work". And I don't see why we need a "Disagree" button either, if you don't "Agree", then you're stuck with that UI and can't move forward to Tobira.

**Comment by owi92** [comment]
@ziegenberg you suggest to distinguish between anonymous and authenticated users. That means that in certain situations, a user would be prompted twice to consent to terms and conditions (before and after login, since every user is anonymous at first).
I would consider that we only ask once (for anonymous users), and do not store anything in the DB.
That means that consent is given per device and not per user (that is how it works on most other websites as well, if I am not mistaken).
If consent per user is a hard requirement for any of you, please let us know.
