### ISSUE TITLE
Loading (and merging) from multiple config files? YAML or JSON5 config files? 

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#1036]
I thought about two things that sys admins setting up Tobira might want? I am mainly creating this issue to see if people are interested in this.

- **Loading from YAML or JSON5 files?** Our configuration library supports those formats, so it should be easy to switch. Only problem is that some comments/docs about config options use TOML syntax which would need to be changed. But would be doable I think. And maybe one doesn't even want Tobira to be configurable in different formats? It "fractures" the ecosystem when everyone uses a different format, making config sharing more difficult?

- **Loading from and merging multiple files?** One might want to put secrets into a separate file (which is encrypted with ansible-vault, for example), while keeping the majority of config unencrypted. Is that something that would be useful to people?

Any opinions? @geichelberger @ziegenberg @Piriya-VM @KatrinIhler @wsmirnow @jduehring (just pinging everyone who once set up a Tobira :D)

**Comment by KatrinIhler** [comment]
>     * **Loading from YAML or JSON5 files?**

I think this is too much work for too little gain. I'm not that familiar with TOML, but it's fine. Also updating your config from the repo for a new release might be harder if you use a different format (or would that repo contain the config in all supported formats?) Either way, I don't really need this.

>     * **Loading from and merging multiple files?**

Same here: We already put secrets in a different file that we encrypt, but using those in the config is pretty easy with Ansible variables, and is also more obvious than maintaining multiple files imo. There might be other use cases for this, but I personally don't need this. ¯\_(ツ)_/¯

**Comment by LukasKalbertodt** [comment]
> or would that repo contain the config in all supported formats?

Yep it would. The `config.toml` template (with all values commented-out) is auto-generated and can easily be generated in different formats as well.

> pretty easy with Ansible variables

Wow, I completely forgot about that, despite having used this workflow a lot in the past :open_mouth: Yeah ok, then the main argument for using multiple files is gone I guess.

**Comment by KatrinIhler** [comment]
> Yep it would. The `config.toml` template (with all values commented-out) is auto-generated and can easily be generated in different formats as well.

Oh cool! Well, I quess then I don't mind either way.

**Comment by geichelberger** [comment]
> > ```
> > * **Loading from YAML or JSON5 files?**
> > ```
> 
> I think this is too much work for too little gain. I'm not that familiar with TOML, but it's fine. Also updating your config from the repo for a new release might be harder if you use a different format (or would that repo contain the config in all supported formats?) Either way, I don't really need this.
> 
> > ```
> > * **Loading from and merging multiple files?**
> > ```
> 
> Same here: We already put secrets in a different file that we encrypt, but using those in the config is pretty easy with Ansible variables, and is also more obvious than maintaining multiple files imo. There might be other use cases for this, but I personally don't need this. ¯\_(ツ)_/¯

+1

**Comment by LukasKalbertodt** [comment]
Well then, I suppose I will close this then. If the features are not that useful, then I gladly go the "less work for us" path :)
