### ISSUE TITLE
Paella isn't using the exact same shade for progress bar and volume control

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1039]
> I wonder why paella isn't using the exact same shade for progress bar and volume control. Didn't even notice this before. And I did have to check with a color picker, as they are very close to each other. But that is a paella thing, nothing to do with this PR.
<img width="836" alt="Bildschirmfoto 2023-12-19 um 11 06 29" src="https://github.com/elan-ev/tobira/assets/94838646/f00ec0c7-0815-4c4b-9297-cf438cbe1d6a">

_Originally posted by @owi92 in https://github.com/elan-ev/tobira/issues/1031#issuecomment-1862482938_

**Comment by LukasKalbertodt** [comment]
Oh wow yeah, I didn't notice this too. Just checked and this is caused by an `opacity: 0.8` on the `progress-indicator-content` div. We would probably have to ask Paella devs whether that's intended. If yes, we can still override that for Tobira.
