### ISSUE TITLE
Use "play-circle" icon in preroll

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1044]
Use
https://lucide.dev/icons/play-circle 
instead of
![grafik](https://github.com/elan-ev/tobira/assets/1752342/9eaf5d46-3eb3-4ce4-aad4-04f8e99a6561)

**Comment by oas777** [comment]
@LukasKalbertodt, is this for you to look into or UPV?

**Comment by LukasKalbertodt** [comment]
I think ideally it should be fixed in https://github.com/polimediaupv/paella-skins so the UPV would need to be involved for sure.

**Comment by oas777** [comment]
https://github.com/polimediaupv/paella-skins/issues/5
