### ISSUE TITLE
Activate "Settings" in Paella 

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1045]
For "Video quality" and "Keyboard shortcuts" to emerge.

**Comment by LukasKalbertodt** [comment]
The settings button/menu is added: https://tobira.opencast.org/v/CDl9MkIV9wq
It is still missing "keyboard shortcuts", but shortcuts in Tobira (including the Pealla ones) are still a bit broken anyway, so this has to be tackled as a separate issue. So can we close this?

**Comment by oas777** [comment]
https://tobira.opencast.org/!v/JePe-XwDwdz says "Yes", I say "Thank you".
