### ISSUE TITLE
Add granular editing permissions to the realm tree

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#1049]
Currently, a user is either Tobira moderator or not, and can thus edit all realms or nothing at all. It's very useful to be able to specify per realm who can edit it, create sub realms and so on. 

To be figured out:
- How are these permissions inherited down the tree? 
  - Not at all? Not really an option I think.
  - A user has permission if to edit a realm if they were given permission to edit that realm or any of its ancestors. Problem: permissions are just additive and you can't take away permissions for sub realms. Consider a communication department that is responsible for the home page. They would necessarily also have permission to everything else, e.g. the physics department page.
  - Maybe just copy permissions of parents when creating new realm, but otherwise no inheritance?
  - ...

**Comment by dagraf** [comment]
I would vote for the second option (A user has permission to edit a realm if they were given permission to edit that realm or any of its ancestors). As far as I know, this behavior is common in cloud services and therefore well known to most users. And every other solution would end up being complicated to manage and explain.

**Comment by LukasKalbertodt** [comment]
> Since David and Olaf favour the second option you have outlined, I'd say we do that. Though I do see the usefulness of the third suggestion (and as a user, would probably expect it to work like that).

Yeah, I think that's a reasonable way to do it. I think we haven't come up with a use case where this model would completely break down. While yes, maybe in my example, the communication department shouldn't edit the physic's page. But since they can edit the home page, they are already very trusted, so they can probably be trusted to not touch pages they shouldn't. And I feel like the "higher page = enough trust to not edit children" would apply in almost all situations. 

But since this is something that was primarily requested by TU Wien: @geichelberger what do you think about this? Is going with "purely additive inherited down the tree" ok for you?


> This can use a (perhaps modified) version of our existing ACL-selector, right? 

Yes, that would be the plan. And yes, the component will get more complex (more branches) due to that but I think it's the way to go.

>The question is whether we differentiate between having the right to [...]

I would say: no.

**Comment by geichelberger** [comment]
> "purely additive inherited down the tree"

That's sufficient. This would allow a scenario that permits you to edit content within a realm without adding new pages or making changes in the `danger zone`. However, you may possess full moderator rights for a particular sub-realm.

```
root
+-- A
+-- B
    +-- ba
+-- C (Edit Content)
    +-- ca
    +-- cb
    +-- cc (Moderator)
        +-- cca
+-- D
```

**Comment by LukasKalbertodt** [comment]
> This would allow a scenario that permits you to edit content within a realm without adding new pages or making changes in the `danger zone`.

Oh okay so you do want more fine grained permissions than just "can do everything" or "nothing". What granularity would be fine for you? To be verbose, here are currently all the things you can change about a page:
- Edit content
- Change name
- Edit order of sub-pages
- Add sub-pages
- Change path segment (danger zone)
- Delete (danger zone)

I would think that separately giving permission for each of those actions is not required. It doesn't need to be that fine grained. 
It totally makes sense to me to make both danger zone actions a separate permission. But what about the others? Which make sense to cluster? One option would be to say "everything else is treated as one", so when giving someone access to a page, then you can chose between 
- "page moderator" (edit content, add subpages, edit settings" and 
- "page admin" (everything including danger zone). 

Or would add more granularity? Like
- "page editor" (edit content)
- "page moderator" (edit content, add subpages, edit settings) and 
- "page admin" (everything including danger zone). 

What's the simplest model that would work for you?

**Comment by LukasKalbertodt** [comment]
I missed one thing that one can do, or rather, will be able to do: edit page permissions! Who can do that? On rather obvious thing: No one can grant another person more permissions than they themselves already have. (E.g. if I am a page moderator, I cannot make my buddy page admin).

Maybe treat "editing realm permissions" like "danger zone" and just let admins control that? Would be the easiest for sure.

Any thoughts on this?

**Comment by geichelberger** [comment]
With "add subpages," it starts to get a bit complicated. Should you be able to rename subpages or only the one you created? All three options are a stretch goal.

Straight forward is:
- "page editor" (edit content)
- "page admin" (everything including danger zone)

**Comment by geichelberger** [comment]
> Maybe treat "editing realm permissions" like "danger zone" and just let admins control that? Would be the easiest for sure.

That's sufficient.
