### ISSUE TITLE
Highlight matches in main search results

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#1065]
When searching for "Peter", then that part of the presenter should be highlighted in the search results. Same for all other metadata fields of course. The style should make sure people can easily see the matches at a glance, but without being super ugly or burning one's eyes.

There are some challenges here since (a) most metadata can be truncated and (b) in the future, some metadata will only be shown if there is a match. So the match influences what metadata is shown and how to truncate metadata. For example, if there is a match at the end of the description, that part should be shown with some context around it. And not just the start of the description. This also briefly came up [here](https://github.com/elan-ev/tobira/pull/1025).

**Comment by oas777** [comment]
As for highlighting keep in mind we probably won't be able to do this when searching slides and transcripts unless we use a timeline representation. This probably requires a clear distinction of "search in DC metadata" vs. "search in video (slides/transcripts)".

**Comment by LukasKalbertodt** [comment]
Yeah, somehow indicating that a match was found in slides/transcripts must work a bit differently than matches in text metadata, true.
