### ISSUE TITLE
Player backward/forward buttons are not balanced

### ISSUE THREAD

**Issue by geichelberger** [elan-ev/tobira#1086]
Maybe I am picky, or my inner monk is ;), but the backward/forward buttons are not optically balanced.

![grafik](https://github.com/elan-ev/tobira/assets/35195803/5cf5dd91-6d30-4056-9e85-d68990d66d17)

**Comment by LukasKalbertodt** [comment]
Can you explain why not? Is it the horizontal distance of the number to the arrow?

**Comment by geichelberger** [comment]
I somehow managed to delete my last sentence. 🙈 The `10` of the forward buttons is too close to the arrow.

**Comment by LukasKalbertodt** [comment]
Yep, fair!
