### ISSUE TITLE
Test database operations (migration in particular) with two Tobira nodes

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#109]
We need to make sure that two nodes don't interfere with one another when modifying the database. The DB migration is a particularly tricky case. See #108.

**Comment by lkiesow** [comment]
Can we lock the database by making this into a larger SQL transaction? Something like:

```
start transaction || lock database;
check if we need migration;
migrate;
end transaction || unlock database;
```

That would do the trick. A second process would then wait until the first one is done and then only very briefly hold the new lock while it is checking if a migration needs to be run.

**Comment by LukasKalbertodt** [comment]
That's actually what we already do. See #108 (or https://github.com/elan-ev/tobira/pull/108/commits/d30bfaa8f10ca965b8e8b2fffcd6cadea946103b). This issue is actually just about testing once that this actually works.

**Comment by LukasKalbertodt** [comment]
To add to this issue: we might want to be even more careful regarding multiple instances. Currently we already do the migration in a transaction and all. But what if an old Tobira version is running on the database and we accidentally start a new Tobira version, which then does some migrations. Now the database is in a state that the old Tobira cannot deal with anymore, and everything breaks. 

We might want to add a kind of lock table, where each Tobira instance adds a row before working with the rest of the database. This row would also contain some information about the state of the database that that Tobira expects. Whenever a new Tobira launches it first checks this lock table and does not run any migrations unless the table is empty. Or something like that.
