### ISSUE TITLE
Download menu

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1095]
![grafik](https://github.com/elan-ev/tobira/assets/1752342/1ff53f4a-f3a3-4619-8ae8-a558ad5fc37d)

The text under "Presentation" (which is a weird term itself) should 

- be one consistent link per line and not two seemingly "broken" links ("video/mp4" and the resolution separated),
- should be in a consistent font where
- the resolution has no grey background and
- should say something like "Video (mp4, 666x666px)"

**Comment by dagraf** [comment]
I agree with everything that Olaf wrote.

One question: What would be needed to make it possible to download a composite video (side-by-side or picture-in-picture) of a dual stream video?

**Comment by owi92** [comment]
I think these are valid requests.

Regarding the term "presentation": Dual stream videos use the terms "presentation" for the slides and "presenter" for the, well, presenter. Single audio and video streams just use the term "presentation".  I think this is coming from opencast and we apdapted the naming convetion, but I am not super happy with these terms either.

Maybe we can just drop the term on single steams (i.e. not use any term). But for dual streams, we still need some distinction, and I am, as always, open for suggestions.

I would refer David's question to @LukasKalbertodt.

**Comment by oas777** [comment]
> I agree with everything that Olaf wrote.
> 
> One question: What would be needed to make it possible to download a composite video (side-by-side or picture-in-picture) of a dual stream video?

I presume you would have to produce such a composite video as part of a workflow in order for it to be available as a download option.

**Comment by oas777** [comment]
> Regarding the term "presentation": Dual stream videos use the terms "presentation" for the slides and "presenter" for the, well, presenter. Single audio and video streams just use the term "presentation". I think this is coming from opencast and we apdapted the naming convention, but I am not super happy with these terms either.

If you're not happy, no one is happy. Can we make us all happy by switching to something like
- Presentation video - Speaker video or
- Video (presentation) - Video (speaker)?

**Comment by LukasKalbertodt** [comment]
> What would be needed to make it possible to download a composite video (side-by-side or picture-in-picture) of a dual stream video?

As Olaf said: that is something that has to be created by a workflow in Opencast. 

---

+1 for dropping the "class" (presentation or presenter) for single stream videos. I'm also fine with all other suggestions.
