### ISSUE TITLE
Problem with "deserialize"

### ISSUE THREAD

**Issue by lukas71** [elan-ev/tobira#1101]
I have this error:
"ERROR tobira::auth::handlers >  Error occured while checking Opencast login data: Could not deserialize `/info/me.json` response"

Could someone give me some information? 
Thanks

**Comment by LukasKalbertodt** [comment]
Hi there! Is there any additional information printed? If so please provide it. That's an interesting error for sure. What Opencast version are you using? 

Further, it would be useful if you could provide the output of `info/me.json` for the user in question. Do you know the login credentials for the user? Like: did you try to login yourself while setting up Tobira or did you find this error in the logs of an already running Tobira? In case of the former: please show the output of `curl -u username:password 'https://youropencast.com/info/me.json'`. With any potentially personal information removed of course.

**Comment by lukas71** [comment]
Hi,
Opencast last (15.1 version) but the problem was from 14.
Tobira starts but problem with auth login with opencast, reported in log 
![Screenshot 2024-02-08 170701](https://github.com/elan-ev/tobira/assets/11831493/49e4a25e-9c56-42fa-a4c9-9e4cbf287e56)
![Screenshot 2024-02-08 170715](https://github.com/elan-ev/tobira/assets/11831493/3296c45e-3409-448a-8d78-b09d8bea7704)

**Comment by LukasKalbertodt** [comment]
Oh hu, I think that's just a Tobira bug introduced in 2ba0dd28eb8f60c246ff83758c13cede1e4c40a8 (which was first released in v2.4). Maybe I added `user_role` there without testing. And the actual field is called `userRole`. Woops. Thanks for reporting! Will be fixed and released as v2.6.

**Comment by lukas71** [comment]
Thankyou very much ...
When do you Think to release 2.6.? ;)

**Comment by lukas71** [comment]
And the problem for tobira sync run....

Harvest request failed: Failed to deserialize API response from https://**********************/tobira/harvest?since=0&preferredAmount=500  Caused by:
                                                    >      missing field `read` at line 1 column 3869

is for the same problem?

Thanks.

**Comment by LukasKalbertodt** [comment]
Oh the harvest error is interesting. Can you tell me what `https://your-opencast.de/tobira/version` returns?

**Comment by LukasKalbertodt** [comment]
I haven't heard back from you yet, but I'm very sure that the linked PR #1109 fixes the harvesting issue you described.
