### ISSUE TITLE
Additional Metadata

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#112]
What exactly are our requirements regarding those? Do they have to be searchable? Fast? Where and how do we need to display them? Do we need to be able to edit them? Etc.

**Comment by LukasKalbertodt** [comment]
Arbitrary metadata for events was added here: https://github.com/elan-ev/tobira/pull/422

**Comment by LukasKalbertodt** [comment]
Will close because I don't see the point of this vague issue anymore given that supported for arbitrary metadata has landed. Further discussion/feature requests in new issues.
