### ISSUE TITLE
Paella Player: Black or white canvas?

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1128]
![grafik](https://github.com/elan-ev/tobira/assets/1752342/b178b404-8ddd-4ffb-b3b5-9f35db6314fe)
https://tobira.opencast.org/events/opencast/2021/graz/v/DsaAHgLOFxG
vs.
![grafik](https://github.com/elan-ev/tobira/assets/1752342/7c39fb41-07ab-49d0-865b-c69f0ce815b6)
https://video.ethz.ch/events/opencast/2021/graz/160a51ca-4e25-4e23-ad3e-65989884f75b.html

Maybe consider in the context of dark/light mode?

**Comment by LukasKalbertodt** [comment]
We discussed this in [this issue](https://github.com/elan-ev/tobira/issues/954) already (and in person) and agreed on the black background.

PS: the specific video example (BBB recording) is also a clusterfuck -> a random black border around the screen capture, but white background for the presenter video. Amazing :D

**Comment by oas777** [comment]
Apologies for bringing this back to the table - did the agreement include the assumption that this can be customised in Paella Player?

**Comment by LukasKalbertodt** [comment]
I'm not sure I get what you are asking, sorry :D 
When we were discussing this, we certainly did not assume that the user could customize this (the background color). We did assume however that it can be customized in Tobira... that was the whole point of the discussion, to decide what color to use in Tobira, hence the implicit assumption that Tobira can even customize it. Or am I missing your point? :thinking:

**Comment by oas777** [comment]
No, you're making my point, i. e. it can be customised in Tobira. Thanks.

**Comment by oas777** [comment]
PS: If you haven't done so already, you should take the issues I open after 10pm with a grain of salt in the future, most of them don't stand the test of daylight.
