### ISSUE TITLE
The future of ROLE_TOBIRA_MODERATOR?

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#1133]
Some recent changes affected what "Tobira moderators" can do:
- #1097 made it so that moderators cannot anymore just edit any non-user page.
- The fix for https://github.com/elan-ev/tobira/security/advisories/GHSA-f9jh-r227-r9qg lead to moderators no longer being able to find unlisted videos (this might have been an unintended side effect...)

Currently, having ROLE_TOBIRA_MODERATOR grants the following privileges:

- Use uploader (also granted via ROLE_TOBIRA_UPLOAD)
- Use Studio (also granted via ROLE_TOBIRA_STUDIO)
- Use the Editor (also granted via ROLE_TOBIRA_EDITOR)
- Find unlisted series, when adding a new series block
- "Mount series" (the thing the admin UI does, not really important here)

For completeness, also note that users with ROLE_ADMIN can do absolutely anything in Tobira.

## Finding unlisted items

The semantics of `searchAll{Series/Events}` (used in the content block editor) are as follows:

- The search never returns items that the user has no read access to. (Note: series `read_roles` are completely ignored right now, see #398, so everyone has read access to all series.)
- The search always returns all videos/series that the user has write access to. 
- Additional, the search also returns all videos/series that are listed. 

And only for the series search and if the user is moderator, the search also returns unlisted series. So effectively all series are returned if you are moderator. That's kind of inconsistent.

Having the ability to find unlisted items can be very useful, e.g. for users that don't necessarily have write access to all videos but can be trusted to manage the home page for example. 

## The future?

So what to do? I have the following thoughts/ideas:

- Having a role per individual privilege sounds like a good idea, to be able to grant those individually. So I think we should add a ROLE_TOBIRA_CAN_FIND_UNLISTED or something like that. Or even two roles for series/events separately? 

- Having a simple role that grants all Tobira-internal privileges also sound convenient. But does that include the ability to edit all non-user pages? And: is ROLE_TOBIRA_MODERATOR that role? Or do we want to introduce a new ROLE_TOBIRA_ADMIN role? I can easily imagine use cases where you want to give full Tobira privileges, without using ROLE_ADMIN, which would also give full Opencast privileges (with read & write access to everything).

Opinions, input and feedback welcome!

**Comment by KatrinIhler** [comment]
I don't really have an opinion here right now, but in general

> Having a role per individual privilege sounds like a good idea, to be able to grant those individually

sounds like a good idea.

In regards to

> I can easily imagine use cases where you want to give full Tobira privileges, without using ROLE_ADMIN

I wonder if this can also be achieved by adding a user to an Opencast group that grants all individual rights necessary?

**Comment by KatrinIhler** [comment]
> No, unless you are using auth.session.from_login_credentials = "opencast" or are otherwise contacting Opencast for roles in your custom auth integration.

Ah, thx.

> is it useful to add a ROLE_TOBIRA_GLOBAL_PAGE_ADMIN that grants the right to edit all non-user pages, like moderators could previously do? 

Yeah, why not. I like granular roles. :D

But in hat case, having a role that grants all those privileges without being an Opencast Admin is probably also a nice thing.

**Comment by LukasKalbertodt** [comment]
I now opened https://github.com/elan-ev/tobira/pull/1137. Please let me know (comment in the PR) whether you think that's a good change. You only need to read the PR description.
