### ISSUE TITLE
Harmonise warning levels/display

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1197]
I see two different levels/intensities of warnings in case you cannot see something you expect to see:

![grafik](https://github.com/elan-ev/tobira/assets/1752342/d2d6f6a7-7da9-4c98-93c5-1b1f8bff5f1b)
vs.
![grafik](https://github.com/elan-ev/tobira/assets/1752342/033e4edd-a75f-4202-a669-792d9fd3d980)

I know the latter is due to videos lacking, but I feel it's a bit too shy, especially if the second part is the reason. Also note the different wording:
"You are not authorized to view this page."
vs.
"you might not be authorized to see them"

**Comment by LukasKalbertodt** [comment]
I suppose we can be more specific with the second error. We should be able to say either "does not contain any events" OR "You are not authorized to see these events". I don't think the information that a series contains events that you cannot see is particularly ... revealing. 

Technical notes: we likely have to extend the API a bit. Maybe just add another `numVideos` field, but ideally without having to send another SQL request for that. Will have to see.

**Comment by owi92** [comment]
The note that @oas777's second screenshot is showing is outdated and doesn't exist anymore in v2.10.
It has been replaced by the following ("Empty series" is the actual series' title and not part of the note):
<img width="1126" alt="Bildschirmfoto 2024-07-16 um 15 14 42" src="https://github.com/user-attachments/assets/2ac31989-10f3-4304-9f8f-9b9166fc9e28">

But this is also shown in cases where there actually are events but a user isn't authorized to see them.

So I would agree with Lukas: we should discriminate between these cases. I'd suggest that we handle it the same as Playlists (see screenshot below):
<img width="1152" alt="Bildschirmfoto 2024-07-16 um 16 28 02" src="https://github.com/user-attachments/assets/5fd9d0f3-b82f-414d-b4be-dcc719ec630f">

**Comment by oas777** [comment]
So you're saying that instead of "No videos" we display "X videos are missing or require additional permission to view." in both scenarios? Doesn't that contradict Lukas saying "We should be able to say either 'does not contain any events' OR 'You are not authorized to see these events'"? Which makes sense because one the user cannot change (there are no videos, go away!), the other he could try to change by logging in to see whether he is authorized.

**Comment by owi92** [comment]
Well now that you put it like that... you are right of course. The thing is that a "missing" video is a special case that is only applicable to playlists anyway, so for series it would just say "x videos require additional permissions to view".

**Comment by owi92** [comment]
Regarding this suggestion made by Lukas:

> in case of "not authorized to view" and if the user is not logged in, we can also show a link to the login page.

I'm not sure if that is necessary or particularly helpful, at least if you are picturing an extra button for this. I am in favor of just adding something like "You might need to login" to the "You are not authorized..." warning.
A direct link to the login page might suggest that this will definetely let the user view the video, which isn't guaranteed and could confuse people if they still can't view some videos after logging in. Maybe we could make the "_login_" word of "You might need to login" act as a link?

**Comment by oas777** [comment]
+1 for the suggestion to link "login".  "You might need to login" is better than "You are not authorized..." because the second one sounds final. Which it might not be if you log in. But what do we show when the user logged in and still isn't authorized? Can we see that status and then tell him "Yep, you're not authorized after all, sorry."?

**Comment by owi92** [comment]
> Can we see that status and then tell him "Yep, you're not authorized after all, sorry."?

If a user is logged in and still not authorized to view some videos, I would just show the "You are not authorized.." without the login addition.
