### ISSUE TITLE
Update juniper to 0.16

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#1198]
https://github.com/graphql-rust/juniper/blob/juniper-v0.16.1/juniper/CHANGELOG.md#0161--2024-04-04

It's probably a rather large and involved update, but we want to update eventually anyway and it gives us at least a newer GraphiQL version, which is neat.

**Comment by owi92** [comment]
done in https://github.com/elan-ev/tobira/pull/1298
