### ISSUE TITLE
Edit everything about the footer

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1202]
Not sure what https://github.com/elan-ev/tobira/pull/336 does, but for the footer, we need the ability

- to remove existing links completely,
- add more internal links (like "About Tobira"),
- edit their respective pages (like https://tobira.opencast.org/~tobira) with links included, and
- allow external links 

to cover information like "Disclaimer", "Copyright", and "Imprint" institutions need to convey.

**Comment by LukasKalbertodt** [comment]
That's exactly what #336 does. All of that is already possible. So I guess I will close this and we see each other in your own internal issue tracker in a few minutes? :grimacing:

**Comment by oas777** [comment]
Not sure what emoji that is, but thanks anyway for the quick answer!
