### ISSUE TITLE
Move config `sync.{user,password}` to `opencast.*`

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#1219]
The sync user+password is by now also used for other purposes, like talking to the external API to delete events. So having them in the `sync` section is not really useful. This will be a breaking change, so I would like to include it in a release that has a breaking change anyway.

Or... add multiple credentials? Like, use different ones for external API and sync for example?

**Comment by owi92** [comment]
> Or... add multiple credentials? Like, use different ones for external API and sync for example?

I would prefer to use the same credentials for both sync and other external API stuff, mainly to keep things simple. Is there a practical reason for splitting these?

**Comment by LukasKalbertodt** [comment]
To be honest: I don't know. We got surprised before by needing to use a special hosts for external API for example. Maybe there are reasons why people want to use different credentials? I suppose it makes not sense for security, because both users need `ROLE_ADMIN` anyway. Might be worth asking in the technical meeting once? Or not ignoring my remark for which I had no concrete basis anyway :shrug:

**Comment by owi92** [comment]
I did not ask in the technical meeting, but yeah, should be fine I think.
