### ISSUE TITLE
Player control bar slightly larger than video

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#1228]
Only on the right side and on "larger" screens. The screenshot was taken on my 14" laptop.
<img width="376" alt="Bildschirmfoto 2024-08-22 um 14 47 03" src="https://github.com/user-attachments/assets/4b385648-7e7d-4c97-8080-07b55d22fcd6">

**Comment by LukasKalbertodt** [comment]
I can't reproduce it in any zoom level here right now. Can you provide more details on how to reproduce it? What does [this website](https://whatismyviewport.com/) say? Does that happen for all videos or just particular ones?

**Comment by owi92** [comment]
Oh you know what, I think this was a result of my screen being squished by dev-tools. Can't reproduce otherwise either. Closing.
