### ISSUE TITLE
Do we want rounded corners on the video player?

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#1229]
I think it looks nicer with rounded corners rather than shap ones 🤷 
Though maybe having sharp corners is deliberate and was decided before I came on board.
However if it is only because paella does it like that, it is possible to override.
<img width="1509" alt="Bildschirmfoto 2024-08-22 um 14 57 56" src="https://github.com/user-attachments/assets/1b168c18-3f61-41cb-8f79-803d51dddb8f">

**Comment by oas777** [comment]
"No, thanks" was my initial response of course. But then I saw most/all (?) other elements have rounded corners, so that's a "Yes" from me for consistency, if it is.

**Comment by owi92** [comment]
> all (?) other elements have rounded corners

I think that is the case. Just out of curiosity, why was your initial response "no, of course not"?
I went back to look at Lisa's design and there the player does actually have rounded corners, though only slightly (which I think works well, maybe better than the radius I used in my screenshot).
Did you veto that back then? I don't remember discussing it to be honest.

**Comment by oas777** [comment]
I don't remember either, but the reason for my initial rejection comes from "preserving" the original video which doesn't have round corners.

**Comment by LukasKalbertodt** [comment]
Interesting, never considered that. You of course have the problem that you cut of a tiny bit of information from the video. But with the small radius that we are talking about, I really can't imagine that being a problem. I would stick to the 4px radius that Lisa suggested though, not using a bigger one. That should already remove the sharpness of the edge. Maybe prepare a PR and we can test out how we all like it?

**Comment by dagraf** [comment]
I would vote for round corners with a small radius. YouTube has them and I never noticed them being there - untill now.

**Comment by owi92** [comment]
We decided against this in https://github.com/elan-ev/tobira/pull/1237 (see comments).
