### ISSUE TITLE
Settings moving away from video canvas when scrolling

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1231]
Mentioned in https://github.com/elan-ev/tobira/issues/1196, this was not solved yet, says https://tobira.opencast.org/!v/JePe-XwDwdz.

![image](https://github.com/user-attachments/assets/bef3a05c-8cbf-4837-adc9-fc356003481a)

**Comment by owi92** [comment]
I opened an issue in the paella repo for that: https://github.com/polimediaupv/paella-core/issues/368
