### ISSUE TITLE
Should the timecode keep updating with the video while we're waiting to create a link / embed code with a start time? 

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1250]
![image](https://github.com/user-attachments/assets/ed75cdbd-2187-4abc-a955-b88e5e23408e)

**Comment by oas777** [comment]
Thanks, Ole. It is a question or a prompt for discussion and maybe others can chime in shortly.

**Comment by LukasKalbertodt** [comment]
I would agree with Ole that it's not really something I would expect. I wouldn't mind either way, but in my opinion this is a very low priority issue as it hardly negatively affects UX, right? So I wouldn't touch it at the moment. But of course, please comment if you disagree.

**Comment by oas777** [comment]
Priorities, right.
