### ISSUE TITLE
Kritischer Fehler - Opencast konnte die Video-Dauer nicht angeben.

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1251]
https://tobira-test-oc.ethz.ch/editor-ui/index.html?id=2d9d6ce2-9325-4fe7-9831-3f469b1e4c7d&callbackUrl=https%3A%2F%2Ftobira.opencast.org%2F%7Emanage%2Fvideos%2FG_LHoAvAYuN&callbackSystem=Tobira+Test+Deployment 

bzw.

https://tobira.opencast.org/!v/G_LHoAvAYuN beim Öffnen des Videoeditors

**Comment by LukasKalbertodt** [comment]
Mhhh, it seems like Opencast has conflicting duration information? In Tobira (engage information) it is shown as 0:13, but the admin UI shows 0:24. @Arnei wanna take a quick look?

**Comment by Arnei** [comment]
Either way the editor is getting a duration of `null`. If I recall correctly, the duration is not taken from the metadata catalog, but from an internal value that Opencast calculates itself (when and how it does that exactly I am unsure about).
