### ISSUE TITLE
A critical error has occurred! A problem occurred during communication with Opencast.  Details:  Status 403: No write access to this event.

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1253]
Ich gehe dann mal ins Wochenende ...

https://tobira-test-oc.ethz.ch/editor-ui/index.html?id=3532d97f-d8ed-45b2-812e-2094743b1daf&callbackUrl=https%3A%2F%2Ftobira.opencast.org%2F%7Emanage%2Fvideos%2FCrk3cpH3Yxg&callbackSystem=Tobira+Test+Deployment

bzw.

https://tobira.opencast.org/!v/Crk3cpH3Yxg beim Öffnen des Editors.

**Comment by oas777** [comment]
PS: Ich bin jeweils als "sabine" angemeldet.

**Comment by LukasKalbertodt** [comment]
This is unfortunately a known problem: https://github.com/elan-ev/tobira/issues/600. In short: waits for JWT stuff, which I'm pushing currently.
