### ISSUE TITLE
Allow for the title text to be removed 

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1269]
In case you have the name/title of your video site in the logo and want to have a video on top.

![image](https://github.com/user-attachments/assets/e9d3fc04-6427-4172-94e1-d1e2c15a6fbf)

**Comment by dagraf** [comment]
+1

Same here in Bern.

<img width="1258" alt="Bildschirmfoto 2024-11-12 um 16 38 43" src="https://github.com/user-attachments/assets/ffbb45fe-3a63-4045-9a48-ee4f8d6f177b">

**Comment by LukasKalbertodt** [comment]
To reduce bloating the configuration too much, I would probably remove this text in 3.0 completely. We only need to provide a way for people to "get that title back" if they want. I see two options:

1. We make it possible to give a name to the root realm (like any other realm). 
2. We solve it via "Title" blocks.

I think I slightly prefer 1, without having thought about it too much. For all other realms, the name is already rendered as a `<h1>` element, which is exactly what we want. It would also make the root realm less special, and fewer special cases are always good (note though that the root realm is still special as a `null` name is allowed, unlike for other realms). 
Title blocks are currently rendered as `<h2>` elements, but having those without a `<h1>` is not great, so we would need to special case "the first title block on the root realm"... which adds special treatment.

**Comment by dagraf** [comment]
I also prefer 1. Like this, we will have a consistent behavior.

**Comment by oas777** [comment]
+1

**Comment by LukasKalbertodt** [comment]
Solved in #1289 (why the heck did it not close this automatically? ...)
