### ISSUE TITLE
Database nitpicks

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#131]
Instead of making a PR for every tiny little DB/SQL thing I notice, here's a place to collect them all and maybe at some point fix them all in one swoop.

* We need "best practices" for `on delete` and `on update` clauses.
* `randomized_ids` should use parameter names instead of the `$n` placeholder syntax.
* Should the `__internal_entity_ids` sequences be `owned by` the tables they belong to?
  * That complicates the usage of the id generation, though.

**Comment by LukasKalbertodt** [comment]
These things are now tricky to change via migrations. And it works for us, so the current state can't be too terrible :D Thus, closing this now
