### ISSUE TITLE
GraphQL schema validation

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#14]
We should run a validator (with reasonable settings) during CI. We might also want to provide this as a script.

**Comment by LukasKalbertodt** [comment]
There are tools that inspect two GraphQL schemas and report whether backwards-incompatible changes are introduced. We probably want to use that once we have a public/released API version. (Though I hope that this moment is fairly late in the development.)

**Comment by LukasKalbertodt** [comment]
Regarding other kinds of validation... I guess we are covered fairly well already. Typescript and Relay already make sure that our queries conform to the schema; defining the actual API in Rust and letting Juniper generate the schema (hopefully) guarantees that the Schema is syntactically and "low level semantics"-valid. So really not sure what we would do. Denouncing to low priority.

**Comment by LukasKalbertodt** [comment]
Possibly relevant: https://github.com/kamilkisiela/graphql-inspector

**Comment by JulianKniephoff** [comment]
> Possibly relevant: https://github.com/kamilkisiela/graphql-inspector

This is now used in #552.

**Comment by LukasKalbertodt** [comment]
With #552 we have a good foundation for these kinds of checks. As the API is not yet stable (and #552 checks the parts where stability is relevant), we can close this. In the future, we might want to extend #552 to other parts of the API (or everything). But this issue probably isn't needed anymore.
