### ISSUE TITLE
Create login system

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#165]
In the end, users should be able to authenticate via different login providers, like LDAP. We need a basic login system for that. Here are some rather unordered thoughts and points from discussions we already had:

- `users` DB table with artificial ID, display name, and others.
- `user_sessions` DB table with user ID and a randomly generated session ID. The session ID is stored in a user's cookie and authenticates the user. The table could also contain meta data about the session or a timestamp when the session expires. 
  - Expired sessions could be cleaned up ... regularly? We can probably just ignore cleanup for now and create an extra issue about that :P 
- Login provider:
  - We briefly thought about being able to associate multiple provider with a single account. But that's (a) lots more work (mostly UI stuff) and (b) potentially confusing for users as they are not used to that. So prooobably not. In most use cases, the organization will probably restrict possible login providers to a single one anyway.
  - This issue does NOT include actually writing a login provider like LDAP. Instead, a dummy provider should be written that's as simple as it can get (e.g. fixed username and password).
  - Presumably we want a `login_provider` column in `users` that has an enum value to specify what login provider this user was created from. We also then need additional columns ... possibly. I imagine that an `login_id` column would be needed which stores some unique ID used in the provider (like the username in many cases). I assume we need this later for authorization. But yeah...

This issue also includes some frontend functions to test the login. Doesn't have to be nice, but it should be able to demonstrate that the login system works.

**Comment by JulianKniephoff** [comment]
@lkiesow brought up an interesting idea regarding this. I hope I can reproduce it halfway decently here:

We could probably drastically simplify the Tobira-side of things if we just accept the fact that authentication will in most cases be handled by external systems anyway, and roll with it. Concretely that could mean that we just have one authentication method in Tobira directly: Accepting a (cryptographically signed) token containing whatever user data we need. These tokens could then be generated by external systems somehow, which would also provide the login UI.

This way, Tobira would basically need to know nothing about different login mechanisms. Specifically, we don't need to have any kind of abstraction and/or plugin mechanism for them in our code.

**Comment by LukasKalbertodt** [comment]
Superseded by #219 and #273
