### ISSUE TITLE
Add Tobira Opencast module (with dummy API)

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#174]
This is the first step in getting the synchronization between Opencast and Tobira going. This issue is just about creating a new module and preparing it so that we can add APIs later. 

We have an Opencast fork specifically for this: https://github.com/elan-ev/opencast-tobira

We probably need to think how exactly we use that fork (e.g. do we use `develop` as main branch; what branch of Opencast do we base this work on? ...).

**Comment by lkiesow** [comment]
First version available in https://github.com/elan-ev/opencast-tobira

**Comment by LukasKalbertodt** [comment]
Oh, this is already done for a while.
