### ISSUE TITLE
Add GET parameter to specify a timestamp for a video (e.g. `t=3m12s`)

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#191]
Basically like YouTube does, we want that as well. Loading such a page would immediately jump to the specified timestamp in the video. I would try to not "naturally generated" these links though. Instead, you would only get such a link when explicitly using a UI element to "set a time" or if you manually edit the link. That's different from YouTube where sometimes (e.g. when you started a video before) the link already contains the timestamp. That leads to me always asking friends "is the timestamp intentional" when they send me videos with timestamp in it. And roughly half of the time it isn't!

**Comment by JulianKniephoff** [comment]
Would this only be supported on the video page or do we wanna be clever about video blocks as well? 🤔

**Comment by LukasKalbertodt** [comment]
Video Pages only for now? I can't think of a nice way how to make it work within realm pages. Adding a second video block then breaks stuff? Naaah
