### ISSUE TITLE
Catch panics and handle errors in `sync` subcommand

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#201]
The `sync` subcommand should start a process that runs forever. A panic or error somewhere in the harvesting code should never lead to the process stopping. As such we need to catch such things fairly high in the call stack.

**Comment by lkiesow** [comment]
Why not just die and restart? Wouldn't that be far simpler?

**Comment by LukasKalbertodt** [comment]
Who would be responsible for restarting it? `systemctl`? If that's easy to do, I'm fine with doing it that way. On the other hand, catching those panic/errors is also not a lot of work and makes Tobira more robust even in the absence of an external thing restarting Tobira.

**Comment by LukasKalbertodt** [comment]
After some experience with this, I also don't think Tobira *should* restart itself automatically. Makes the Tobira code more involved. A complete restart is the cleanest anyway. And one should really only run that as a service so there is always something else that can restart Tobira. So... closing.
