### ISSUE TITLE
Data and Data Structures

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/tobira#23]
Ideas
-----

- _Page_ structure is a graph
    - Enforce tree
        - Let's start with this
        - Julian may create showcase later
        - Or maybe DAG? But now multiple URLs to same content/realm
    - _Page_ can have _elements_
    - _Page_ can have sub-pages
- _Elements_ (content-boxes?) have a type
    - Store data as JSON?
    - Use a document database?
- _Video_
    - Video metadata
    - Parent series
- _Series_
    - Series metadtata
- Source of video data is Opencast
- Source of Video metadata is Opencast
- Push notifications with fallback

Communication
-------------

- Opencast SHOULD push new updates to Tobira
- Opencast MUST keep track of changes and when they happen about:
    - Published videos
    - Video metadata
    - Access control lists
- The set of pushed and persisted information is not necessarily the same
    - Updated metadata needs to be persisted and pushed
    - Updated workflow operation may not be that important
- Tobira MUST keep track of its last full update

#### Opencast

- Create a Tobira API service in Opencast
- Get information from necessary services
- API to get updates since X
    - Can be used to get _all_ updates
- API to synchronously update metadata
    - Returns the updated data
    - Used by video and series blocks
- API to ingest new video
    - With metadata
    - Returns workflow summary
- API to synchronously create/update new series
    - Returns the updated data
- API to delete series/event

#### Tobira

- API to receive update messages
- API to get structure
- APT to create new series page?

### Random Thoughts

- Use Apache Kafka?
    - It guarantees that messages reach the destination.
    - It supports replay.
    - Probably rather not
- Database type
    - Use PostgreSQL's JSON type?
        - Vermnutlich einfach PostgreSQL
        - https://www.postgresql.org/docs/9.5/textsearch.html
    - Use MongoDB?
    - Use Elasticsearch?
    - One or more database types?
        - Eher eine Datenbank

**Comment by LukasKalbertodt** [comment]
This is mostly implemented, outdated or superseded (in particular, by #175). Will close.
