### ISSUE TITLE
Investigate why deploy WF ran for external contributor

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#231]
See https://github.com/elan-ev/tobira/pull/229#issuecomment-878533718

I did not expect the deploy WF to run for this PR. After all we have this check:

https://github.com/elan-ev/tobira/blob/35bfb94526773238aa514920ac2923124cead6d7/.github/workflows/deploy.yml#L12-L17

So either the check is buggy or I was the `actor`. But why? I need to investigate that at some point.

**Comment by lkiesow** [comment]
Doesn't data is pulled from the context the workflow is run it?
```
        github.actor == 'LukasKalbertodt' ||
        github.actor == 'JulianKniephoff' ||
        github.actor == 'lkiesow'
```
That context should be the default branch of this repository. So, I think, the workflow is only run if one of these is the author of the last commit on the default branch.
