### ISSUE TITLE
Should we commit the generated GraphQL schema?

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#28]
The cons are obviously that it's generated and we can always recreate it. And keeping it in version control can lead to inconsistencies.

I don't know whether there are any pros, but it's not impossible there are some, like for `package-lock.json`. We might want to think about that.

**Comment by LukasKalbertodt** [comment]
We discussed this a few weeks ago (when you were on vacation) and decided for "let's not commit it" -- at least for now. 

My main argument *for* committing it was that people could work on the frontend without having Rust installed. But we concluded that (a) that won't happen a lot, (b) to work on a project, you can expect developers to install dependencies and stuff like that, and (c) installing Rust really isn't that hard. Additionally, we might want to have the schema downloadable from a running Tobira. That means that once we have a public test server later, frontend developers could develop against that and also use its schema.

Regarding your lockfile argument: I think I understand what you are getting at, but I think the logic doesn't really apply here. The Rust code should exactly describe the API, so the graphql schema file does not add any information.

**Comment by JulianKniephoff** [comment]
Fair enough. The question then becomes: Should we `.gitignore` it?

**Comment by LukasKalbertodt** [comment]
I guess so? Files that are created as part of the build process should either be ignored or checked in, right? I certainly don't want a dirty workspace all the time :P

**Comment by JulianKniephoff** [comment]
Nevermind, it already is, because we ignore `frontend/build` of course ... :sweat_smile:
