### ISSUE TITLE
Improvements of "my videos" page

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#319]
- [ ] https://github.com/elan-ev/tobira/issues/371
- [ ] https://github.com/elan-ev/tobira/issues/356
- [ ] https://github.com/elan-ev/tobira/issues/403
- [x] Show public links of your video (where it's embedded + under username, e.g. `/@peter/v/123`)
  - [ ] Instead of just showing referencing realms, show video links. And also make direct link less prominent? What link do we want people to share?
- [x] On the public/normal video page, if the user can edit the video, show a button "manage video" to get to the `/~manage/videos/123` page directly.
- [ ] Maybe add note to the top saying that all videos which one can edit are shown. This is to avoid users asking the support "that's not my video!". Or generally adopt a different "user <-> video" association.

**Less important**
- [ ] Bulk operations (e.g. delete multiple videos at once)
- [ ] Maybe scroll to the top on pagination

**Comment by dagraf** [comment]
Further improvements:
- [ ] Make it possible to search for only the videos in the page "my videos"
- [ ] Offer addtional column "Series"

**Comment by LukasKalbertodt** [comment]
I split this issue into multiple single ones for easier tracking:

- #530 
- #529 
- #528 
- #527 

I ignored the "less important" things in my top comment for now. There are plenty of other things one could do anyway. We will just create issues once they come up/are needed.
