### ISSUE TITLE
New Series Block should automatically get title from series

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/tobira#327]
If a user adds a new series block and selects a series to display
or if the current title was identically to the title of the previously selected series,
the series block should automatically assume the title of the series.

We already have good metadata for the series, and it's unnecessarily annoying to have to enter identical metadata twice.

**Comment by lkiesow** [comment]
Actually… we may even want to remove the title entirely and always take the series title.
There will be an edge case where someone might want to change it, but it will mostly be annoying to have to keep this metadata twice and ensure it's synced properly (e.g. what happens if someone changes the series title in Opencast)

**Comment by LukasKalbertodt** [comment]
If you leave the title field empty, the title of the series is used. But I agree, this could be improved a lot.

**Comment by lkiesow** [comment]
I've already [brought this up on pull request #328](https://github.com/elan-ev/tobira/pull/328#issuecomment-1033754622) but post it here again to keep track of it:

The more I think about this, the more Im in favor of not allowing to set a custom title.

> If you leave the title field empty, the title of the series is used. But I agree, this could be improved a lot.

That's not something anyone will understand right now, given the current user interface and allowing that might be nice in a few very special cases, but that also comes with a whole bag of disadvantages and usability challenges:

- (Usability) Why do I need to manage the same metadata twice? That is, if user's understand that these are separate metadata.
- (Usability) Need to communicate to users when exactly titles will change? What are the conditions? What if I change this in Opencast? What if I want to change it in the player?
- (Usability) Is the current title a title tracked by Tobira or Opencast? That's hard to understand and nearly impossible to communicate without users checking each block by entering its edit mode.
    - Why does a title sometimes not change if I edit the title in Opencast
    - I have changed this video's title, why did the metadata not change in Opencast(, the next time I include this, in the player, …)?
- (Usability) Easily leads to mismatching metadata at several places.
- (Technical complexity) Need a mechanism for determining when to update titles if someone changes the title in Opencast

Overall, I think this is much harder to implement and communicate properly and may easily lead to problems with not much gain and no required use-case brought up so far I know of.

**Comment by JulianKniephoff** [comment]
Closing in favor of #335 as per our recent discussion.
