### ISSUE TITLE
Add some form of direct link route with series UUID

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#359]
A common requirement by external tools is having a fixed URL for Tobira that just includes a series' UUID and renders some information about the series. We need to add such a route. We likely also want to add the same with the Tobira ID instead of the series UUID. 

It's still unclear what the route would do exactly:
- Either show information about the series directly
- Or forward to another route where the series is mounted on

**Comment by dagraf** [comment]
Note: This direct link must be desplayed in den Opencast Admin-UI and must be able to build also in ILIAS (see screenshot for recent config possibility in ILIAS).
<img width="855" alt="Bildschirmfoto 2022-03-21 um 10 26 05" src="https://user-images.githubusercontent.com/15246287/159234440-795e0907-6bf7-4018-ae5e-c354f13f6008.png">
