### ISSUE TITLE
Make series findable via search

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#360]
Series should appear in search results when searching for their title

**Comment by oas777** [comment]
Isn't that the case already? Cf. https://tobira.opencast.org/~search?q=Latsis.

**Comment by LukasKalbertodt** [comment]
What you are seeing there are *pages*. This is of course confusing as many pages have the same name as a series and only the series is shown on those pages. So for those, it is indeed not a problem. But imagine a series that doesn't have a dedicated page in the page structure: that cannot be found via search currently. 

Of course, adding this feature (making series findable), we should take care that we won't show the series AND the page for that series, as that would be confusing for users.
