### ISSUE TITLE
Make live videos work (well)

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#365]
We have never tested Tobira with live videos. Most stuff should just work, as live events are just events, BUT we really need to try things out. Lots of stuff might need adjustment: maybe live videos have no track information? Maybe the URL needs to be handled differently and put into the players differently.

Also, Tobira might want to know about live events in order to show a nice "live" widget on the thumbnail. Or generally be more aware of this attribute of an event. In that case, we need to transmit more data from Opencast.

**Comment by dagraf** [comment]
Two important specs:

1. The live streams events are displayed in Tobira from the moment of planning with an indication of when the event starts.
2. The location of the live stream events can be identified and communicated as a link from the moment of planning.

**Comment by LukasKalbertodt** [comment]
This issue was closed by the linked PR, but that doesn't yet mean that necessarily everything works perfectly now. I think most stuff should work, and the foundational work is done. Everything else we just have to test with real streaming setups and identify problems then.
