### ISSUE TITLE
Paella Player: Show video sections 

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#368]
Sometimes Opencast segments the video into sections, e.g. based on slide detection. We should use that information and pass it to the player and potentially also render something ourselves.

**Comment by oas777** [comment]
Stumbled upon this gem: Does this information really go via Tobira? I thought this is information Paella gets from Opencast. The other way round, I didn't see any slide preview only just now... which is definitively unacceptable.

**Comment by oas777** [comment]
I think there's a misunderstanding here, Manuel: This is about the absence of slide previews created automatically, either as hover-over in the timeline
![grafik](https://github.com/elan-ev/tobira/assets/1752342/b93fc511-047b-40b8-9bf4-e9801155caa5)
or a separate line.
![grafik](https://github.com/elan-ev/tobira/assets/1752342/bbbfcb8c-2adf-44cd-b84c-bbba6e7c3ece)

We know you want a chapter editor, but this is not the ticket to ride ...

**Comment by owi92** [comment]
Done in https://github.com/elan-ev/tobira/pull/1163
