### ISSUE TITLE
Tobira fails to start if the search service is unavailable

### ISSUE THREAD

**Issue by geichelberger** [elan-ev/tobira#394]
If the search service is not available, Tobira fails to start. This behavior is unexcepted as searching is only one aspect of Tobira.
Furthermore, it unnecessarily increases administrative effort if the systems have to be started in a specific order.

```
2022-04-04 13:57:42.495 ERROR tobira >  failed to connect to MeiliSearch
                                      >  
                                      >  Caused by:
                                      >      0: failed to connect to MeiliSearch at 'http://127.0.0.1:7700'
                                      >      1: Cannot reach MeiliSearch: The Meilisearch server can't be reached.
 ▶▶▶ Error: failed to connect to MeiliSearch
 Caused by:
  ‣ failed to connect to MeiliSearch at 'http://127.0.0.1:7700'
    ‣ Cannot reach MeiliSearch: The Meilisearch server can't be reached.

```
**Expected behavior:**
Tobira can be (re)started, even if the search service is unavailable.
Log a warning that the service is unreachable.

**Comment by LukasKalbertodt** [comment]
First, I :+1:ed your suggestion, but thinking about it, there are a few problems, unfortunately. 

The main one has to do with "index preparation". Tobira, when connecting to Meili, tries to create all required indexes (without data!) and configures them. Without this automatic preparation, there are a lot of problems. Even if we do the preparation lazily when we actually have to talk to Meili, we have a few problems. And in case of `tobira worker` or `tobira search-index *`, we might very quickly (within milliseconds) need to talk to Meili, so there is not really an advantage then.

> This behavior is unexcepted as searching is only one aspect of Tobira.

This is true and might be temporarily annoying when setting up Tobira. But in the end, in production, one always wants to have the search enabled. So setting up Meili search is required anyway.

> Furthermore, it unnecessarily increases administrative effort if the systems have to be started in a specific order.

Yes, but this effort should be fairly small (one `After` entry in the service file, for example). And as said above, something like `tobira worker` (which you want to start on boot as well) could require Meili after a few milliseconds, so just skipping the startup check won't help here.

Any thoughts on this? This is not a final decision yet -- I would like Tobira to be able to start without Meili. But we have not found a good way to do it.
