### ISSUE TITLE
Potentially implement more (direct) links to view videos and series

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#399]
We already have `/!v/<tobira-id>` and with #397 we will get `/!s/:<opencast-id>`. There is also `/realm/path/v/<tobira-id>`, of course. We might at some point want to "complete the matrix" of routes for looking at a video/series, within its realm/directly, using the Opencast/Tobira ID. :shrug: 

- [x] `/!v/:<opencast-id>`
- [x] `/!s/<tobira-id>`
- [ ] `/realm/path/s/<tobira-id>` (in case that's ever gonna be useful)

**Comment by LukasKalbertodt** [comment]
`/!s/` done in 2d4bdc22b162487ab92497277041a9bf767d69e4

**Comment by LukasKalbertodt** [comment]
`/!v/:<opencast-id>` done in 03513b7201f6fe326533c7b1bdcda7a6f4188154

**Comment by LukasKalbertodt** [comment]
I would say that we don't need to track `/realm/path/s/<tobira-id>` here with an issue. If it becomes relevant, we can talk about it then.
