### ISSUE TITLE
Video metadata 'by' shows only the last presenter

### ISSUE THREAD

**Issue by geichelberger** [elan-ev/tobira#407]
The metadata contains 2 presenters:
![grafik](https://user-images.githubusercontent.com/35195803/163120510-411cdb0f-bf29-45a4-92db-aed7d80e5df2.png)

Only the last one is displayed:
![grafik](https://user-images.githubusercontent.com/35195803/163120438-2ab4001a-ed31-4e73-9450-273ebc56bf9c.png)

**Comment by LukasKalbertodt** [comment]
We knew about this and I will probably fix that next week.

**Comment by LukasKalbertodt** [comment]
@geichelberger this is fixed now, but you need to also update the Tobira module.
