### ISSUE TITLE
Pagination of the video list for users

### ISSUE THREAD

**Issue by mdorferf** [elan-ev/tobira#445]
Hi,
thank you for the work you put into Tobira! 

During our tests, we noticed the following things with regard to usability: 
If a user has many videos, the list of videos becomes very long. This is particularly apparent when users want to add videos to a page. Here, a configuration option with regard to the number of videos per page would be very helpful (pagination). 

Thank you for your help in advance and keep up the great work!

Best regards
Maria Dorfer-Frick (TU Wien)

**Comment by LukasKalbertodt** [comment]
Hi! What list are you talking about? The "my videos"? Because that should already be paginated. You are probably talking about the drop-down menu when adding a new video to a page, right? And yeah, that's quite terrible right now :D We certainly want to improve that.

**Comment by mdorferf** [comment]
Hi,
thank you for the very quick response :-) Thank you for asking, it is indeed the drop-down menu when adding a new video to a page. An improvement is very helpful as this is likely to cause problems for users with many videos.
Best regards 
Maria Dorfer-Frick

**Comment by LukasKalbertodt** [comment]
I just noticed that we already have an issue for that: https://github.com/elan-ev/tobira/issues/373
