### ISSUE TITLE
"Critical error" when leaving "edit realm content" page while editing series or video block

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#457]
To reproduce:
- Login as moderator
- Click "edit realm content"
- Click on "add series/video block"
- Do not select a series/video, but immediately press "View page"
- Press "ok" in the browser "unsaved data" popup
- You briefly see the page, then the critical error

**Comment by JulianKniephoff** [comment]
Seems like the temporary block is not removed when you leave the page like that. 🤔

**Comment by JulianKniephoff** [comment]
> Seems like the temporary block is not removed when you leave the page like that. thinking

This suspicion is further supported by:

a) Not selecting a series/video in the above procedure is actually irrelevant, and
b) Things also get weird for text and title blocks, but "later", if you try to go back to the editor after doing the above procedure with one of those block types.
