### ISSUE TITLE
Prefilled search field does not start the search by pressing enter

### ISSUE THREAD

**Issue by geichelberger** [elan-ev/tobira#463]
I would expect to search again after entering the search field and press enter.

**Current behavior:**
1. Search for cats
2. Click on the first cat video
3. Watch it
4. Want to see a different one
5. Enter the search field and press enter
6. Nothing happens :crying_cat_face: 

**Expected behavior:**
- To see the cat search result

**Comment by LukasKalbertodt** [comment]
Fixed in #574
