### ISSUE TITLE
Add opencast previews as player poster image

### ISSUE THREAD

**Issue by geichelberger** [elan-ev/tobira#464]
If videos start with a fade-in, the player shows an empty screen.
For a better user experience, it would be nice to set the opencast previews as the poster image.

![grafik](https://user-images.githubusercontent.com/35195803/175981727-4e95c795-747f-4c98-8fcf-f7e95b7218eb.png)

**Comment by JulianKniephoff** [comment]
Some initial thoughts from @LukasKalbertodt (originally from #547):

> Currently the video player simply shows the first frame of the video, which is usually black. We could instead show a splash screen (the same as the thumbnail) there. At least I assume Paella can be configured to do so. (And even if not, we could potentially do it ourselves even).
>
> However, we should likely add a new database column for the url to the splash image, as it should have a higher resolution. Opencast does not currently provide any higher quality images than the one we already used for the thumbnail. Compare https://github.com/opencast/opencast/issues/3753. We could also add a generic column `images` with a json structure with potentially multiple images, giving us more flexibility in the future without having to change columns all the time. But not sure.

**Comment by LukasKalbertodt** [comment]
As we decided we just implemented the simple option as its better than a black player. For further improvements I opened this issue: https://github.com/elan-ev/tobira/issues/712
