### ISSUE TITLE
Can't navigate from a critical error

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#471]
Try for example to go back after trying to reproduce #457.

**Comment by JulianKniephoff** [comment]
Good point. :thinking: Would removing the `popstack` handler have any unintended side effects?

**Comment by LukasKalbertodt** [comment]
I don't think so, I just think it would be complicated doing that. Again, we have to assume all our JS is broken somehow.

**Comment by LukasKalbertodt** [comment]
So can we close this?

**Comment by JulianKniephoff** [comment]
OK so I looked into this for a few minutes. The `popstate` handler **is** actually unregistered. However, browsers apparently just don't treat history entries created with `pushState` like "normal" history entries created by navigation. That is, they will only ever fire `popstate` events for them when you hit "back", never actually perform a navigation only because there's no handler for that event.

So there isn't actually anything we can (easily) do here. I still think it's annoying, but I guess I can live with it somehow. x)
