### ISSUE TITLE
Series title can overlap block controls in page editor

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#495]
![image](https://user-images.githubusercontent.com/123272/181572326-b6df49f8-6526-4ad8-963c-8273dec48b8e.png)

**Comment by JulianKniephoff** [comment]
The easy solution is to just raise the `z-index` of the button group, but then that might cover the title, of course. :thinking:

**Comment by LukasKalbertodt** [comment]
This doesn't happen anymore since the title is displayed differently now:

![image](https://github.com/elan-ev/tobira/assets/7419664/574fb883-9324-48ed-b64d-8d2dc5caf631)
