### ISSUE TITLE
Connecting Tobira to the ETH course login system

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#538]
Setting up everything so that users can log into Tobira with ETH's authentication system.

**Comment by oas777** [comment]
To be more precise, this might touch upon SWITCH AAI, LDAP ETH and the local course authentication infrastructure.

**Comment by LukasKalbertodt** [comment]
This is done already and this repository is also not really the right place to track this anyway. Closing.

**Comment by oas777** [comment]
Well, it's not done with respect to " local course authentication infrastructure, but that's not your fault or issue right now.
