### ISSUE TITLE
Setup some backend benchmarks

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#548]
Having some benchmarks to automatically evaluate the performance of Tobira would be useful, especially to check impact of specific changes (e.g. switching to musl or using jemalloc, see #116). But it's also useful to have a rough idea of how many users Tobira can handle.

Of course, a few caveats:
- In reality, other servers are delivering images and videos that are required for a seamless user experience. For that and other reasons, it's not really possible to easily assess the performance of the fully integrated system as a whole. 
- A majority of the time used answering graphql requests is spent in the DB.
- I don't think anyone expects the Tobira backend code itself to be a problem at all (except maybe the DB queries).

I think it still makes sense to have some benchmarks, but yes, it's not highly important at all.

---

As to *how*: there are [quite a number of HTTP benchmarking libraries](https://github.com/denji/awesome-http-benchmark). Some rather focus on low level performance (not really intending to test application logic), e.g. to benchmark HTTP frameworks or servers (see: [wrk2](https://github.com/giltene/wrk2), [oha](https://github.com/hatoo/oha), [rewrk](https://github.com/lnx-search/rewrk)). Others again focus on DOS testing by sending special, potentially invalid HTTP requests. And finally there are those that focus on testing somewhat-close-to-reality "user interactions" by letting one specify what HTTP request a user would send.

For Tobira, the third category is most relevant, I think. There are still quite a lot of these, but I found three interesting ones:

- https://github.com/tag1consulting/goose (Rust scripts)
- https://github.com/mcollina/autocannon (JS scripts)
- https://github.com/fcsonline/drill (yaml scripts)

My idea would be to write a few useful benchmarking suites (including very simple ones, but also ones getting close to realistic user behavior) and commit them into this repo.

Julian also had the idea to script a browser to perform a number of specific user action (e.g. "navigate to 'lectures'"), let the browser record all requests done, and generate a benchmark script from that. It would get us closer to the "benchmarking an actual user story" as having a fixed list of HTTP requests (usually against `/graphql`) will diverge from what the actual frontend is requesting. But even ignoring that this would likely take a lot more time to setup, I still think fixed benchmark scripts have a value. And we likely just want to start with that anyway -- the fancy autogenerated benchmarks can always added on top. And not to forget: the user-interaction browser script likely also needs updating from time to time when the UI changes.

**Comment by JulianKniephoff** [comment]
For the record, I don't think it would take "a lot more" time. 😝
