### ISSUE TITLE
Provide framework/library to writing custom login handlers

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#550]
While flexible, Tobira's login system requires quite some setup. To make it easier for adopters to get started and save everyone's time, it would be nice to have a good starting point for writing such a login handler. (This issue is purely about login handler, i.e. using Tobira's login page and session management.)

In our test deployment we use `util/containers/login-handler.py`. My first idea was to just extract the common plumbing code as a Python module. Unfortunately, I forgot that `http.server` has this note: "Warning: `http.server` is not recommended for production. It only implements basic security checks" ([link](https://docs.python.org/3/library/http.server.html)). It's not clearly described why this warning exists or whether it applies to us. But I guess it would be better to not tell Tobira users to use such a script.

It's rather inconvenient to code this logic in the webserver config directly. And most people would feel more comfortable coding some Python or another well-known language instead of weirdly (ab)using a webserver config. I see three viable options:

- **Python + a proper HTTP lib**. Unfortunately, such a lib is not included in the standard library, meaning we need some external lib that needs to be installed with pip or something. Not a huge problem, but less convenient than having it in std. 

- **JavaScript + Node**. It's really easy to get a simple HTTP server going with Node. And it's easy to install Node on most systems, or it's possibly already installed. JS is a very common language, so most people would feel comfortable enough using it.

- **JavaScript + Deno**. Deno is the new JS runtime in town, made from lots of Node devs that wanted to do it "right this time". Apart from many other cool features, for us there are mainly two advantages: (1) it can execute TypeScript directly, so we can just write our lib/framework in TS, having one language fewer in our repo (since our frontend is already TS). (2) It supports remote imports, e.g. `import { ... } from "https://.../";`, meaning that including our lib would be really easy (without even saying `npm install` or so). The main disadvantage is that it's less common than Node, making installing it on a server slightly harder (tho still easy).

I think I would like to use the Deno solution because of having fewer languages in this repo, ease of including our dependency, and trying cool new stuff.

**Comment by JulianKniephoff** [comment]
While I'm **for** deno in all fairness it should be said that in production you are still going to want to cache the dependencies locally.

One could additionally provide a `Dockerfile` that does this and that also replaces the rarer `deno` dependency with the much more common `docker`. 🤷‍♀️

**Comment by LukasKalbertodt** [comment]
Deno does cache these dependencies automatically: https://deno.land/manual@v1.25.2/linking_to_external_code

**Comment by JulianKniephoff** [comment]
It also recommends vendoring them manually for production, though: https://deno.land/manual@v1.25.2/linking_to_external_code#but-what-if-the-host-of-the-url-goes-down-the-source-wont-be-available

**Comment by lkiesow** [comment]
Just my few cents here: Not a hard no, but I'm actually against deno

 Not only is it uncommon and therefore harder to run, the goal here is to have something users can easily modify and feel comfortable with. In a lot of cases, these users are also less actual developers, but SysOps and/or DevOps people. Cool new stuff people are unfamiliar with is therefore what I would rather avoid if at all possible.

In fact, Python is far more common among DevOps/SysOps and would be my first choice. But node is well established and still okay.
