### ISSUE TITLE
Do not make videos uploaded public by default

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#555]
At least that's what the text "Hinweis: Hier hochgeladene Videos sind öffentlich, d.h. sie können von allen angeschaut werden." indicates.

**Comment by LukasKalbertodt** [comment]
This is basically #369. Making videos public by default is just a workaround for the current lack of ACL selector. With no way to change the ACL of a video in Tobira, making it private by default means the video cannot be shared at all, i.e. is useless. So yes, this will be fixed with #369.
