### ISSUE TITLE
Better response to `/favicon.ico`

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#563]
Chrome (and presumably other browsers as well) just request this path hoping to find a favicon there. Our favicon lives elsewhere. We currently reply with our `index.html` to that as it could be a realm path. It would be nice to have a better response, e.g. 404. Related: #437

**Comment by JulianKniephoff** [comment]
You can also specify an alternative (preferred) favicon location in a `link` tag. That only works if people request HTML resources, of course; not for example if they view an image directly.

Apart from the logo we don't currently have any interesting non-HTML-resources, though, I think; all the videos, thumbnails, potentially attachments in the future, etc. are/will be served by Opencast.

**Comment by LukasKalbertodt** [comment]
Ok fair. I noticed it when having the `/~metrics` endpoint open in the browser. And for graphiql we can't add a `link` tag presumably. So mh. I guess I still would want to have a better reply to `favicon.ico`? We need #437 anyway
