### ISSUE TITLE
Integrate `relay-compiler` into Webpack

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#62]
In #29 I tried to integrate the Relay codegen into the Webpack build, but unfortunately I wasn't very successful. I can't do anything about it, I think, and am basically waiting for a fix from the appropriate Webpack plugin project. If that ever lands, I would still like to do this.

Here is some additional info quoted from #29:

> * Integrating Relay into the build was a bit awkward
>   [...]
>   * If we want to use the [Webpack plugin](https://www.npmjs.com/package/relay-compiler-webpack-plugin), we need to match its version of the `graphql` dependency because of relay-tools/relay-compiler-webpack-plugin#56
>     * I even had to `npm dedupe` to make sure that there is only one physical version of the package in the `node_modules`-tree
>     * We could of course run this build step outside of Webpack, especially once we have a proper task runner

**Comment by JulianKniephoff** [comment]
One thing to think about here is that this would mean that Webpack and `tsc` can't run in parallel anymore.

**Comment by LukasKalbertodt** [comment]
> One thing to think about here is that this would mean that Webpack and `tsc` can't run in parallel anymore.

For that reason I would rather not integrate relay into webpack. Currently, the relay compiler runs in 0.6s, typechecking in 1.5s, linting in 0.9s, webpack in 3.9s. The latter three can run in parallel, but all three have to wait for the relay compiler. Having type checking and linting after webpack would add 1.5s to the incremental build time. I'd like to avoid that.

**Comment by LukasKalbertodt** [comment]
Disregard the opinion I stated in the previous comment. There is value in integrating it into webpack if we use `webpack watch`. So we just tried it and it unfortunately still didn't work.

```
npm install --save-dev relay-compiler-webpack-plugin graphql
```

Add this to `webpack.config.js`:

```js
const RelayCompilerLanguageTypescript = require('relay-compiler-language-typescript').default
const RelayCompilerWebpackPlugin = require('relay-compiler-webpack-plugin')
```

And in the `plugins` array:

```js
plugins: [
    // ...
    new RelayCompilerWebpackPlugin({
        ...require('./relay.config'),
        languagePlugin: RelayCompilerLanguageTypescript,
    }),
],
```

Running `npx webpack --mode=development` results in this weird error

```

ERROR in ./src/page/Realm.tsx
Module not found: Error: Internal Error: _parseObjectTypeNode: Cannot create object type 'Event' defined as a client type.
 @ ./src/page/Realm.tsx 17:77-121
 @ ./src/App.tsx
 @ ./src/index.tsx

ERROR in ./src/page/Video.tsx
Module not found: Error: Internal Error: _parseObjectTypeNode: Cannot create object type 'Event' defined as a client type.
 @ ./src/page/Video.tsx 14:77-121
 @ ./src/App.tsx
 @ ./src/index.tsx

ERROR in ./src/page/Home.tsx
Module not found: Error: Internal Error: _parseObjectTypeNode: Cannot create object type 'Event' defined as a client type.
 @ ./src/page/Home.tsx 11:74-117
 @ ./src/App.tsx
 @ ./src/index.tsx

ERROR in ./src/ui/Blocks.tsx
Module not found: Error: Internal Error: _parseObjectTypeNode: Cannot create object type 'Event' defined as a client type.
 @ ./src/ui/Blocks.tsx 18:81-128
 @ ./src/page/Realm.tsx
 @ ./src/App.tsx
 @ ./src/index.tsx
```

The error seems to originate [here](https://github.com/facebook/relay/blob/4b78c7dd27b286f9ee8f5b993ccb160163956999/packages/relay-compiler/core/Schema.js#L1549-L1566) but that doesn't really help us.

Other notes: the `src`, `artificactDirectory` and `schema` fields have to be the same in the plugin config and in `relay.config.js`. The code above does that, but failing to do so leads to other strange errors. At least we think this is correct.

---

So we gave up for now.

**Comment by LukasKalbertodt** [comment]
FWIW, if we wanted to have our own dumb plugin, it should work roughly like this:

```js
class MyPlugin {
  // Define `apply` as its prototype method which is supplied with compiler as its argument
  apply(compiler) {
    compiler.hooks.beforeCompile.tapAsync(
      'MyPlugin',
      (compilation, callback) => {
        const { spawn } = require('child_process');
        const process = spawn('npx', ['relay-compiler']);
        process.stdout.on('data', (data) => {
          console.log(`relay: ${data}`);
        });
        process.on('close', callback);
      }
    );
  }
}

module.exports = MyPlugin;
```

**Comment by JulianKniephoff** [comment]
Since I'm still assigned this issue, and I'm trying to clean up my GitHub a bit, I'ma go ahead and close this for now. Looking at the repo of the plugin, nothing has changed since last year. It's also not even officially endorsed by Relay or anything. Plus, we have a working setup for now. :shrug:
