### ISSUE TITLE
Speed up ESLint (using incremental TypeScript stuff?)

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#63]
Of the three parallel tasks `floof` currently runs during development, ESLint actually turned out to be the slowest. (Thanks, @LukasKalbertodt for the measurements.)

I have an inkling that the TypeScript rules might not make use of the incremental build stuff introduced by #44. We might want to look into this.

**Comment by LukasKalbertodt** [comment]
It might also be worth it looking into `deno_lint`: https://github.com/denoland/deno_lint
It's supposed to be waay faster than eslint (think 2.4s -> 50ms). And:

> Supports `recommended` set of rules from ESLint and `@typescript-eslint` out of the box with no config.

**Comment by LukasKalbertodt** [comment]
With https://github.com/elan-ev/tobira/pull/184, the eslint runtime is a lot less now. Measuring the three commands that run in parallel again, eslint is as fast/slow as `webpack`. So optimizing eslint won't decrease total runtime right now. 

Should we just close this issue?

**Comment by JulianKniephoff** [comment]
I spent 5 minutes researching and couldn't find anything. :shrug:
