### ISSUE TITLE
Maybe take a look into using swc instead of webpack

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#64]
> swc is a super-fast typescript / javascript compiler written in rust.

`swc` is a webpack replacement written in Rust that is way faster than webpack: https://github.com/swc-project/swc

I don't know if we could use it: we currently use a lot of webpack plugins that may or may not work with or exist for swc. But making these rebuilds way faster might be worth looking into it.

**Comment by JulianKniephoff** [comment]
Webpack 5 got also recently released, and is supposedly faster, due to better caching and things like that. We might also migrate there and see whether things are already fast enough. x)

**Comment by LukasKalbertodt** [comment]
Somehow I confused stuff. swc is mainly a replacement for babel, not webpack. It also has "spack", which is a bundler, but yeah, the main project is about babel-like transformations. The transformation actually supports everything we currently use and can read browserlist automatically. It's pretty sweet. It reduces the webpack build times from 3.9s to 3.4s on my machine.

However, the generated code errors in the browser with "`React` is not defined". Potentially fixable, but already not a good sign if switching from babel to swc results in broken code. Further, running `webpack --mode=production` leads to `swc` panicking... badly:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ecmascript/transforms/compat/src/es2015/regenerator/case.rs:873:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

So, let's not switch to SWC for now :D
