### ISSUE TITLE
Language selection not obvious to screen reader

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/tobira#657]
The language selection menu contains different languages which may or may not be selection. The selection is indicated by a check mark in front of the option. This information is not being transferred to screen readers which will just read the languages.

An easy way to transfer this information would be [an ARIA checkbox role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role) with `aria-checked` being set or unset:

```html
<li tabindex="0"
    role="checkbox"
    aria-checked="true">
  <svg …>…</svg>
  <div>English</div>
</li>
```

This should also fix the second problem that right now, users get no feedback at all when actually selecting another language. So you don't know if your choice was accepted before you start tabbing though other interface elements again.

![Screenshot from 2023-01-12 22-26-23](https://user-images.githubusercontent.com/1008395/212187465-070a8540-243e-49b8-87ad-d6fdb3a392b5.png)

**Comment by owi92** [comment]
Fixed in https://github.com/elan-ev/tobira/pull/774
