### ISSUE TITLE
E-Mail notifications once an upload is complete

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#672]
This is a feature requested by the ETH. It is unclear which part of the whole software stack should be responsible for this. I think Opencast should do E-Mail notifications. Tobira does currently not have an email for users and has also no capabilities to send mails. That would add quite a bit of complexity to it all.

However, we are not done with it by saying "ok Opencast should do it". How does Opencast get the user E-Mail? The upload is done via a temporary JWT user. Opencast could look up a mail address for a specific username, but uff. Or Tobira does need to know about E-Mails? And what if we want a checkbox in Tobira for users to select whether they want e-mail notifications? Lots of open questions.

**Comment by oas777** [comment]
Alternatively, an information should be provided in Tobira.

**Comment by LukasKalbertodt** [comment]
So yes, the ETH successfully configured their workflows to send email notifications. This is helped by #1268. 

The text might still be changed in the future, but that's not the highest priority and we are waiting for other changes (like #556 and #444).
