### ISSUE TITLE
Add option to specify series in the uploader

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#675]
Fairly straight forward: users might want to directly upload a video into a series. Technically, specifying that in the metadata catalog is easy. We need a searchable select box for that. Thus, I think #360 is a blocker for this. 

Regarding "what series can be seen": people decided that we can simply use the series `write` ACL here. Make the series selectable here iff the user has write access.

**Comment by dagraf** [comment]
Discussion im meeting:

- It will be configurable if a series must be specified while uploading.
- When no series gets specified the uploaded event will end up without any connection to a series.

After this first implementation further discussion is needed if a connection to a 'user's series' is needed (if no series gets specified).
