### ISSUE TITLE
If a user is on the `/~upload` page and navigates there again, that should probably reset the page

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#681]
This came out of #633.

I have two thoughts here:

* Have some kind of callback mechanism where the router calls a function provided by the route when it is navigated to, even when it is the current route?
  * Doesn't this already exist?
* A very simple workaround would be to unconditionally rerender the current route on navigation. This could be as simple as #680.

Thoughts?

**Comment by LukasKalbertodt** [comment]
I think we can go the unconditional route for now. If `rauta` ever becomes a standalone library, one might want to add an option to modify that behavior. But I think for us always rerendering is fine. That's indeed the expected behavior I think, as normal `<a>` links work like that, right?

**Comment by JulianKniephoff** [comment]
I guess then I'm just gonna undraft #680. :smile:
