### ISSUE TITLE
Player: Improve usability by showing end of timeline and by changing cursor to hand when hovering over clickable regions

### ISSUE THREAD

**Issue by dagraf** [elan-ev/tobira#707]
Currently, users do not get a hint that they can click on the timeline (because there is no change of the cursor when hovering over it and because the existence of a timeline is not indicated). This also makes it hard to jump directly to the end of the video, because this end is not shown. In fact, it is not at the right border of the video, but some pixels more to the left.

Suggested improvements:
- Implement changing of the cursor (from an arrow to a hand) when a user hovers over the timeline.
- Indicate the whole timeline (for example, with e red border that gets shown when a user clicks into the timeline, see screenshot for how it is shown in the Paella Player in Opencast).

<img width="853" alt="Bildschirmfoto 2023-02-14 um 10 35 29" src="https://user-images.githubusercontent.com/15246287/218696570-f29bfcf8-7ce3-43ac-8a22-9ea5f878fbfb.png">

**Comment by LukasKalbertodt** [comment]
I agree with everything you said. Unfortunately, this is not really something we can do, as this is purely the Paella player. I would refer you to their repository, but they are currently in the process of implementing a completely new design. Therefore I think it's best for us to wait till they are done with that, and then testing that. We will update Tobira's Paella player as soon as the new design is somewhat stable.

**Comment by LukasKalbertodt** [comment]
I just tested this again with the new design. I think it's better, but still not perfect. For example, the cursor does not change on timeline hover. Nor does it change on button hover, for that matter. 

So I think this is worth creating an issue in [this repository](https://github.com/polimediaupv/paella-core). Will you do that? I can do it too, if you prefer.

**Comment by oas777** [comment]
Are we sure it's not [this repository](https://github.com/polimediaupv/paella-ethz/issues)?

**Comment by LukasKalbertodt** [comment]
I'm not 100% sure, but since the lack of cursor-change was already present in the old design and is something that should be fixed for both, I think mine is more appropriate. But :shrug:

**Comment by dagraf** [comment]
@LukasKalbertodt It would be great if you could create an issue in the other repository. Thx!

**Comment by LukasKalbertodt** [comment]
Should be solved by this PR: https://github.com/polimediaupv/paella-skins/pull/4
