### ISSUE TITLE
How does configuration work?

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/tobira#76]
We should prepare Tobira to be deployed in a dynamic environment which means that there may be multiple instances, … This might have an effect on configuring Tobira. Another question is if we want to be able to modify certain aspects of the configuration from the front-end (admin area; configuration panel). This doesn't matter for aitomated deployments but is highly requested when doing a manual installation.

Questions:

- Do we keep everything in a configuration file?
- Will there be two configuration files (backend and frontend)
- Is the front-end configuration always public (like with Opencast Studio)
- Do we keep/transfer configuration to a central place (e.g. Database)

Thoughts:
- Using a database allows us to configure via the frontend
- Using a database potentially allows for a configuration wizard
- There should be a way for automated deployments
    - Maybe deactivate front-end configuration for what is set in a configuration file?

**Comment by LukasKalbertodt** [comment]
I thought about this a lot. We should also discuss this next time we meet!

> Do we keep everything in a configuration file?

We already talked about how environment variables would be handy and how they are commonly used in the "container"-world. However, I think that we need a file anyway since we might want to specify longer strings and or other files. Assuming we need a config file for other stuff anyway, then I would say that we should not use environment variables anymore, but instead keep everything in the file. Having multiple sources of configurations makes everything a lot more complex and we suddenly have to think about which source overwrites which other source and how to merge values.

> Will there be two configuration files (backend and frontend)
> Is the front-end configuration always public (like with Opencast Studio)

I want to avoid the frontend having to load its own static config file from somewhere. All configurations relevant for the frontend can simply be send through the `index.html` (which can be dynamically generated/adjusted by the backend).

And I think I would like to keep everything in one file.

**Comment by LukasKalbertodt** [comment]
I guess it would help to just have specific examples of what users might want to configure. I will start a list of things I can think of. Feel free to edit this list by editing my comment! This list can include a wide range of things that could be considered "configuration". We can later decide which of those should be in a config file and which should be configurable via UI.

- DB connection: 
  - URL, database, user, password
  - Maybe stuff like "how many concurrent connections"
- HTTP Server: 
  - on what port/socket address to listen
- Opencast connection
  - URL to admin server, auth data
  - Maybe some settings about how often to sync and stuff like that
- Design
  - Logo/Favicon
  - Title/meta information
  - Custom CSS
- Logging (log file path, log level, ...)

**Comment by lkiesow** [comment]
This is a hopefully faithful summary of what we discussed about this at the last developer meeting.

Random things:
- No environment variables or at least only in rare cases
- Separate front- and back-end configuration
- Front-end configuration is considered public

We have two types of admins:
- Occasional admins who set up Tobira manually. They want
    - Touch no configuration file if possible
    - A graphical configuration wizard
    - Change settings in a graphical admin interface later
- DevOps who automate everything anyway. They want
    - Set everything via configuration file for automated deployment
    - Want to be able to automatically set a known good state (don't let users override stuff on the fly)

The idea was to use a combination of configuration file and frontend:
- Keep configuration in database
    - Things can be changed in a front-end ui
- Configuration files set values as well
    - Configuration files are loaded into the database
    - Whatever is set if a configuration file is fixed and is read-only in the front-end

Additional thought (Lars):
- Do we need hot-loading of configuration?
    - Only if Tobira starts slow

**Comment by JulianKniephoff** [comment]
> * Do we need hot-loading of configuration?
>   * Only if Tobira starts slow

Random unqualified thought: Startup time might even be irrelevant when *something something* Kubernetes *something something* rolling updates, right? :sweat_smile:

**Comment by lkiesow** [comment]
But we will not only have k8s environments. Keeping below 5s (←semi-random number) would be nice.

**Comment by LukasKalbertodt** [comment]
Below 5s should totally be possible! Hot reloading adds a whole new world of things that can break by watching a file and stuff like that. So I'd prefer not to. But again, I doubt startup time would be a problem.

**Comment by LukasKalbertodt** [comment]
> Separate front- and back-end configuration

I don't think we talked about that. My approach would be to not consider those two separate configs. If the frontend needs access to some configuration, then the backend somehow has to send that information to the frontend. And I would suggest embedding that into the `index.html` on the fly. (We can't really insert into `bundle.js` and I don't want the frontend to make an HTTP request just for a tiny config file.)

> Front-end configuration is considered public

I think there is no way around that. Stuff that the frontend code can read, the user's browser can also read and thus the user can read it, too. You can make it harder for the user, but I think it's fundamentally public. 

---

With that I think the only open point of discussion is the "at some point we want users to configure some things via the UI". Right? In which case: maybe we want to open a separate issue for that and close this one?

**Comment by LukasKalbertodt** [comment]
As explained in the previous comment: I will close this issue now. Configuration via UI can be considered at a later stage.
