### ISSUE TITLE
"Verwalten": Change colour?

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#801]
https://pr792.tobira.opencast.org/!v/JIY8Mv2B44J: Is there a reason "Verwalten" is bluish while "Download" and "Teilen" are black?

**Comment by owi92** [comment]
The "Verwalten" button acts as a link while the other buttons each open a popup. We had some feedback that users were confused about the fact that both use the same style, even though they do different things.

So the different color (which is used on other links as well) is a way of how one could distinguish the two different button types. But if that is also/even more confusing, then it might be worth exploring different options.
