### ISSUE TITLE
Metadata: Rearrange display

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#802]
![image](https://user-images.githubusercontent.com/1752342/235786533-06aed58b-78ed-4631-a804-736c29fe3792.png)

With the line breaks in the right "window" of metadata, I wonder whether we should create two equally wide "windows" for metadata so that they can be presented in one line. Keep in mind the "description" in the left "window" might be significantly longer so you might want to restrict the maximum number of lines with a "more".

**Comment by LukasKalbertodt** [comment]
This should be done in #792. The metadata label and value are in one line now. The two grey boxes are not always equally wide, but rather adaptive to their contents. But should be fine now. If you disagree, feel free to reopen this issue.

**Comment by oas777** [comment]
Lukas, closing this will result in me not remembering to check whether it has been implemented. Could we find another way for you to discard issues at the end of a task, yet keep them alive so that owners can check?

**Comment by oas777** [comment]
Can you close and (re-)assign to David and me for testing?

**Comment by oas777** [comment]
Looks good to me. David?

**Comment by oas777** [comment]
PS: Also with long descriptions, cf. https://tobira.opencast.org/lectures/d-phys/2019/autumn/402-0023-01L/v/JM-UhPTvA6V.

**Comment by dagraf** [comment]
Looks good to me, too. Therefore, I close this issue (again).
