### ISSUE TITLE
Open design issues: Discussion with Lisa

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#805]
- Symbols coherent a) in Tobira and b) between Tobira, Paella Player, Editor, and Studio?

![image](https://user-images.githubusercontent.com/1752342/235926932-725425bb-512d-4581-aa76-16149017f25b.png)

- Color scheme: Different color for links (vs. pop-ups)
- Wording coherent (DE/EN)?

**Comment by dagraf** [comment]
Wording is not coherent. See my suggestions in this comment: https://github.com/elan-ev/tobira/issues/808#issuecomment-1542519006

**Comment by LukasKalbertodt** [comment]
I suppose this can be closed now? Our contract with Lisa has long ended and I think most of these points were discussed at some point.

**Comment by oas777** [comment]
Correct.
