### ISSUE TITLE
Paella playback speed button is broken

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#816]
This is nothing new, but maybe we should finally create an issue for this.

![image](https://github.com/elan-ev/tobira/assets/7419664/1c07b8b5-b97e-4a4f-9037-ce48dcb2747c)

This is not correct. I took a quick look bit didn't find anything obvious.

**Comment by oas777** [comment]
Maybe we should talk about Paella 7/ethz instead of fixing this legacy version?

**Comment by LukasKalbertodt** [comment]
This is fixed in the new redesign.
