### ISSUE TITLE
Check should acknowledge about what credentials is using

### ISSUE THREAD

**Issue by mliradelc** [elan-ev/tobira#828]
While configuring tobira, the check parameter gave me an error, saying there is no access to `{presentation_node}/tobira/version`

I was very confused why, because that endpoint has `Role_Anonymous`. After debbuging opencast I realized that Tobira tries to authenticate with Opencast with the user in the config file. After checking the name and password, Tobira Check passed without issues.

From this "problem",  `tobira check` should show with what credentials will access to opencast.

**Comment by LukasKalbertodt** [comment]
I'm very hesitant to print the password anywhere. But if I understand your description correctly, just showing "trying to authenticate as 'admin'" would have already helped, correct?

**Comment by mliradelc** [comment]
Yes, totally, something like, using user "OpencastUser" to authenticate with opencast node "www.example.com"
