### ISSUE TITLE
Clean up translations (move strings around)

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#841]
Over time, the structure of our translation files has gotten a bit... unorganized. Not too bad, but it could use some moving things around.

- Try to have no top-level strings (instead move those to fitting specific children or `general`)
- Move strings around to more fitting locations
- Deduplicate some strings maybe?
- Maybe check for unused strings (see also #271)

**Comment by oas777** [comment]
Where are these "translation files"? Are they the answer to my question in https://github.com/elan-ev/tobira/issues/857?

**Comment by LukasKalbertodt** [comment]
Ole already answered this [here](https://github.com/elan-ev/tobira/issues/857#issuecomment-1554397523) (translation files are [here](https://github.com/elan-ev/tobira/tree/master/frontend/src/i18n/locales)). This issue is just some technical issue with no user-facing consequences.
