### ISSUE TITLE
Safari: description on video page isn't truncated

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#845]
Not sure what's at play there, but the method we use to limit the inital box size obviously doesn't work in safari.

**Comment by LukasKalbertodt** [comment]
What Safari did you test with? Works for me on iOS 16.4.1

Well... it is unusually high, but it gets expanded further when I click the button.

**Comment by owi92** [comment]
Any desktop version basically. Check `tour of the moon` for instance. The text isn't truncated at all.

**Comment by owi92** [comment]
> Well... it is unusually high, but it gets expanded further when I click the button.

Can confirm that this is also the case with safari desktop now. I think fixing this would require more browser specific code in order not to affect other browsers, where it is working as intended. Which I would rather avoid.
So I don't think this needs fixing anymore and we can close this issue.

**Comment by LukasKalbertodt** [comment]
Oh yeah, since Safari 17, the text is truncated now. (Tested in browser stack.) It also seems like the height is fine. So yeah, since it seems to have been a safari bug (and Tobira is still usable in older Safaris), I agree we can close this.
