### ISSUE TITLE
Input element of radio buttons: Also slightly broken on desktop safari

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#846]
This is another kind of broken than described in #836. They appear to be slightly cut off at certain screen sizes.

<img width="462" alt="Bildschirmfoto 2023-05-15 um 17 45 22" src="https://github.com/elan-ev/tobira/assets/94838646/c3ac8748-3600-45b8-a5a4-c029bed5635c">

<img width="146" alt="Bildschirmfoto 2023-05-15 um 17 45 42" src="https://github.com/elan-ev/tobira/assets/94838646/ccbe2545-c19c-40ea-9e04-ddaf328bf8dc">

**Comment by owi92** [comment]
These safari issues... 🤦 
This appears to be an older issue, which never got fixed for some reason. The workaround mentioned [here](https://stackoverflow.com/questions/24957554/theres-clipping-on-the-left-side-of-my-radio-buttons-in-chrome) unfortunately doesn't seem to work.
The only thing that does is making the radio buttons smaller, which I don't want to do.

This clipping only happens when resizing my window and on standard screen sizes it appears to be fine. So this is really just an edge case and I'd propose closing this issue without a fix.

**Comment by LukasKalbertodt** [comment]
I'm fine with that!

**Comment by dagraf** [comment]
Me too.
