### ISSUE TITLE
Chrome: burger menu breaks on very narrow screens

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#848]
This starts happing at widths below 320px. The screenshot was taken at a width of 300px.
It's not a very common screensize but if devices like the galaxy fold are getting more popular, that might change.
<img width="327" alt="Bildschirmfoto 2023-05-15 um 18 56 00" src="https://github.com/elan-ev/tobira/assets/94838646/89557fc8-fdb7-48b2-9383-e46f24aeb286">

**Comment by LukasKalbertodt** [comment]
We only support screens 320px or wider (see [these docs](https://elan-ev.github.io/tobira/supported-browsers)). Do you have a galaxy fold? How does it get to such a narrow screen size? When I researched this back then, 320px width seemed already like a very low estimate of modern devices.
