### ISSUE TITLE
Show more metadata or link to video page on video blocks

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#854]
Video blocks (when a video is included in a page) currently only show the title (if enabled) and the actual video. But users might want to see more metadata and share the video. We could either show this, in a collapsed-by-default box below the video. But I think it's more useful if we simply include a small link below the video saying "go to video page ->" or something like that. That solves all problems in one go.

**Comment by oas777** [comment]
+1 for "simply include a small link below the video saying "go to video page ->" or something like that."

**Comment by dagraf** [comment]
+1 I would suggest to make the including of this link also editable (in the same way as the title). Meaning: Offer a checkbox when inserting/editing a video block saying: "Show link to video page blow video" (or something like that)
