### ISSUE TITLE
Consider hiding text "Drag and drop video files to upload" on mobile devices in uploader

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#859]
Most mobile devices don't support drag&drop, right? I am not sure about tablets or something like that? But we likely want to just hide the one sentence talking about drag&drop on mobile devices then. Then there is just one clear button "select files", which is better I think.

Ideally there would be a check whether the device offers drag & drop functionality. (Like `cursor-precision` media query). But I somewhat doubt there is, so we likely just have to use a "close enough" test.

**Comment by owi92** [comment]
Closed since we couldn't find a viable solution for this. Most if not all mobile devices appear to support drag and drop anyway (however impractical that may or may not be on such small screens).
