### ISSUE TITLE
Direct links to videos or series: If login needed to see them, users should be redirected to the correct page after login

### ISSUE THREAD

**Issue by dagraf** [elan-ev/tobira#874]
At the moment, if I open a link to a series or video which I can only see after a login I get directed to the landing page of tobira when I did log in. Therefore, users need to open the same link again.

Solution: When opening a link is followed by a login, users should be redirected to the page where the hit on "Login".

**Comment by LukasKalbertodt** [comment]
Note: this works on tobira.opencast.org already. For example try [this video](https://tobira.opencast.org/v/DGaLDchO6DJ) and then logging in as `sabine`.

This is thus only a problem for Tobira installation where the `login_link` is overwritten in the config (like in Bern). But I think Tobira itself can be improved, it's not just a "fix your integration" answer. So this issue certainly should be kept open. 

Related PR: https://github.com/elan-ev/tobira/pull/623
@owi92 you even mentioned that in your PR description. I think it should be possible to just also write the previous page to `localStorage` when clicking on the normal `<a>` link to the login page. Maybe you could take a look at this?

**Comment by LukasKalbertodt** [comment]
I was mistaken! Tobira already fully supports this use case. I just checked your integration (Bern) and noticed that there is some leftover code that causes the problem with your installation. I created an appropriate issue in our internal GitLab (186).
