### ISSUE TITLE
QR modal doesn't close when clicking outside of it

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#879]

**Comment by LukasKalbertodt** [comment]
Mhhh what other modals are there? All the "are you sure removal?" modals. Mhh. It doesn't hurt if they close, but I wouldn't necessarily expect them to. Are there others?

**Comment by owi92** [comment]
No I think that's it. Let's keep them like that for now and I'll take a look at the QR modal.
