### ISSUE TITLE
Font for "Copy to clickboard" tooltip on "my videos" page is monofont

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#880]
It should be the normal body font.

**Comment by owi92** [comment]
I think this should also change the link itself to not use monofont. This would make this field coherent to the one used in the `share` menu on the video page.

**Comment by LukasKalbertodt** [comment]
Ah interesting, didn't notice that difference. I see a use in using monofont for links (as then, all characters are clearly distinguishable), but I doubt it's relevant. People just copy and paste it, right? So yeah, I don't care about that I think.

**Comment by owi92** [comment]
Right, makes sense. I think I do actually prefer monofont for these links... so I guess I'll change it in the `share` menu instead, or rather make this the default for copyable inputs.
