### ISSUE TITLE
Page "Videodetails": Link the shown "Referencing pages" to the video itself and not the referencing page

### ISSUE THREAD

**Issue by dagraf** [elan-ev/tobira#882]
If I hit on one of the "Referencing pages" shown in the page "Videodetails" a land on those shown pages. If this page contains multiple videos or even series I end up looking quite some time until I find the video I was looking for (see for example "Startseite" in the shown screenshot). Therefore, I suggest we link here not to the page "Data Modelling and Databases" (see screenshot) but to the video that is embedded on this page (breadcrumb: > Data Modelling and Databases > Tour of the Moon (NASA).

![Videodetails](https://github.com/elan-ev/tobira/assets/15246287/708c86b6-d63e-42c0-a238-fba433e4f105)

**Comment by oas777** [comment]
You mean linking https://tobira.opencast.org/lectures/d-infk/2019/spring/252-0063-00L/v/L5CUekz9uQ0? TThis also reminds me we have to look into the difference between "being part of a series" and "being referenced in a page" for a video.
