### ISSUE TITLE
A once-started search can only be closed by clicking on something or on the "Back" option of the browser

### ISSUE THREAD

**Issue by dagraf** [elan-ev/tobira#883]
If I start to type in the search box, found videos are shown immediately, which is great. But if I want to stop my search and want to get back to the view from where I started my search, I have to hit the "Back" button of my browser. This is confusing because the search results show up so quickly that I did not realize that I have been sent to a new "search result" page.

My suggestion: When I delete everything a have written in the search box I land where I started my search. At the moment, I end up being stuck on this "search result page". Maybe we could add a delete button ('x') which shows up at the very right side of the search box as soon as I have started to type something. Hitting this 'x' deletes what I have written and I land where I started my search

**Comment by LukasKalbertodt** [comment]
Yeah, the frontend part of the search experience is still pretty crap :/ I wanted to improve this for ages, but it was never prioritized. Note that we are tracking this thing and many more in https://github.com/elan-ev/tobira/issues/389 already. But your issue explains the problem in more detail, so let's keep it open.
