### ISSUE TITLE
Video duration is incorrect

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#884]
https://tobira.opencast.org/~search?q=lukas says https://tobira.opencast.org/lectures/d-itet/2017/spring/227-0052-10L/v/IIftDAzUqrN is 3 seconds long where it's longer actually.

**Comment by LukasKalbertodt** [comment]
This is due to use using `event.getDcDuration` in the Opencast Tobira module. This returns the wrong value for this specific event. We should likely retrieve the duration value directly from the dublin core catalog instead.

**Comment by LukasKalbertodt** [comment]
The underlying cause is solved now. Just for your information: you will still see these incorrect times on tobira.opencast.org for some time, but that's just an effect of how specifically our test deployment is setup. Just so you don't wonder how it's still broken.
