### ISSUE TITLE
Maybe include debug symbols in release builds?

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#91]
Rust by default removes all debug symbols in release builds. But at some point, we probably have to debug a problem that occurs in production. And with debug symbols, we at least get file locations with our stack traces. ([`debug = 1` should be sufficient for that](https://doc.rust-lang.org/cargo/reference/profiles.html#debug).) Given that the only disadvantage is a larger binary (which is not really important for the use cases), we should probably enable debug symbols in release builds. 

I will get some specific numbers on the file size in the near future.

**Comment by lkiesow** [comment]
We are in the business of dealing with large files anyway ;-P
Larger binaries shouldn't really matter much.

**Comment by LukasKalbertodt** [comment]
Good point :D 

I did some measurements now:
- standard debug build: 93 MB
- **release build (no symbols): 13 MB** (a)
- release build (no symbols) stripped: 8 MB
- release build (debug=1 all deps): 46 MB
- **release build (debug=1 only tobira): 28 MB** (b)
- release build (debug=1 only tobira with fat LTO): 19 MB
- **release build (debug=1 only tobira with fat LTO, codgen-units=1): 18 MB** (c)

The bold lines (a), (b) and (c) are relevant options. The first one is the current state: no debug symbols. The second bold line is if we only add debug symbols for our own code, but not our dependencies. The last bold line configures some options to reduce the file size (plus producing slightly faster code) at the expense of compile time (this is only for release builds!). We are talking a compile time (without dependencies) of 11s vs. 1m10s -- quite substantial. 

Also note that about 2MB of that file size is just the embedded frontend code (the vast majority of that is just the `bundle.js.map`, i.e. debug infos :P).

What do you think? I would go with (b) or (c) to get the debug symbols, but I don't really care which one of those two.

**Comment by lkiesow** [comment]
Thinking about this for a second, as a packager (at least for RPMs) you would actually build your packages with full build symbols but then strip them and package them separately. I haven't actually looked at how that works (ever) since that happens magically (I have used this quite often). The effect is that you end up with a `tool.rpm` and a `tool-debuginfo.rpm` and you get proper stack traces, … if you install the latter. I bet that there are macros for doing that for Rust as well and we don't need to think about this.

**Comment by lkiesow** [comment]
Looks like it. They are explicitly prohibiting a debuginfo being built for libraries. They wouldn't do that if it wouldn't be created.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/
