### ISSUE TITLE
Tobira seems not to send a label to Opencast Studio when opening it

### ISSUE THREAD

**Issue by dagraf** [elan-ev/tobira#910]
Edit, 17.8.2023:

When opening Opencast Studio in Tobira, it seems like Tobira does not send a label to Studio where this users comes from.

Observations:
- Coming from Tobira: When I download a video on the "Almost done" page, the button at the bottom shows "Finish and return to previous page". Clicking on it takes me back to Tobira. 
- NOT coming from Tobira: This button is called "Exit and back (Admin UI)".

**Comment by oas777** [comment]
> When opening Opencast Studio in Tobira, it seems like Tobira does not send a label to Studio where this users comes from.
> 
> Observations:
> 
>     * Coming from Tobira: When I download a video on the "Almost done" page, the button at the bottom shows "Finish and return to previous page". Clicking on it takes me back to Tobira.
> 
>     * Coming from Tobira: This button is called "Exit and back (Admin UI)".

Is the second option supposed to say "NOT coming from Tobira"?

**Comment by owi92** [comment]
I might be wrong but I think this needs to be configured in Studio and not Tobira (see the [[return](https://github.com/elan-ev/opencast-studio/blob/901acb2e70bc31beab1945401ccc844ccf5e268f/CONFIGURATION.md?plain=1#L148)] section in https://github.com/elan-ev/opencast-studio/blob/master/CONFIGURATION.md).
I don't have any experience in configuring Studio, so hopefully @LukasKalbertodt can tell you how to do this exactly, if the above link isn't helping.

**Comment by LukasKalbertodt** [comment]
You can pass Studio configurations via the URL. I can take this issue, hopefully fixing it this week still.

**Comment by owi92** [comment]
Update: Deployments are working again, thanks to Lukas.
