### ISSUE TITLE
Page setting: Derive name from video or series doesn't (always) work

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#920]
It works for me,

https://github.com/elan-ev/tobira/assets/1752342/54274f5b-6e92-44d8-a210-dbe995ffd099

but not for my colleague:

![Bildschirmfoto_2023-08-18_um_12 09 19](https://github.com/elan-ev/tobira/assets/1752342/e2807a14-a6d8-4537-b93a-468b78fefde5)

Can someone please check whether re-naming a page works reliably?

**Comment by Melanie-Koller** [comment]
I've just seen, that this problem only exists at "my page". On sub pages ist works properly. 

On my page i add some videos and then i like to derive name from one of these videos. This is not working. "Name directly" is working.

**Comment by LukasKalbertodt** [comment]
Ahh ok, thanks for the details. This bug is already solved by #860. This is released as v2.1 and I assume you are testing on v2.0. Testing on tobira.opencast.org works for example. So I will close this issue. If you still have problems after updating to 2.1, feel free to reopen.
