### ISSUE TITLE
Implement Playlists (once Opencast has them)

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#937]
#357 was about developing a concept for playlists. Which was done. This issue is about implementing them in Tobira once they land in Opencast. This will not happen this year anymore! I am just creating this issue to already collect some notes. We might even split this issue into sub issues as there is quite a bit to do.

What does "add playlists to Tobira" mean?

- [ ] Synchronizing playlist data with Opencast
- [ ] Being able to have "playlist blocks" on pages that look pretty much like the current "series blocks"
- [ ] Section "my playlists" where one can create and edit playlists
- [ ] Adding playlists to the search
- [ ] Adding route to playlist

**Comment by oas777** [comment]
Thanks, Lukas. Some quick thoughts:
- Don't add playlists to search (results) where videos by themselves would (also) appear. Keep it simple.
- Plan for videos to "disappear" from playlists for different reasons (deletion, access rights). 
- Keep it simple.
