### ISSUE TITLE
Highlighting video upon hover-over

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#945]
Did we always have this effect on hover-over I just saw at https://tobira.opencast.org/lectures/d-infk/2019/autumn/263-3010-00L?

![grafik](https://github.com/elan-ev/tobira/assets/1752342/0533e4b6-c71a-4dc4-821a-d8b240711ea9)

**Comment by LukasKalbertodt** [comment]
I'm not exactly sure I understand your question. But yes. We had that for a very long time already (since before 1.0). And it's everywhere, not only on the page you posted.

**Comment by oas777** [comment]
Right, thanks. @dagraf, do you like this effect? I don't, even if they are symmetrical (cf. [images](https://ethz.ch/de.html)), but this one even more because it's not.

**Comment by dagraf** [comment]
I have no strong opinion here. Looking at the screenshot, I do not like it very much. But when actually hovering over a video and seeing the effect appear and disappear, I do like it more.

**Comment by LukasKalbertodt** [comment]
I'd argue that the element Lisa's comment was about is quite different from this situation here. 

I not necessarily arguing for having such a flashy animation. In fact, some time ago (before 2.0 I think), I asked internally what people think of it, suggesting to make it less flashy. But the majority was in favor of keeping it. 
I would probably argue against removing it now: it has been part of Tobira for a very long time. And it surely can't be that terrible if you only noticed now, right? And Lisa didn't say anything about this specifically. We could still ask her about this, right?

**Comment by LukasKalbertodt** [comment]
Lisa's answer:

> Aus UX-Sicht sieht man so sehr deutlich welches Video gerade aktiv ist. Also super. Das vergrößern würde ich auf jeden Fall behalten. Die Kippung ist tatsächlich Geschmacksache. Es ist mal etwas anderes, sehr tobiraspezifisch und gibt der Plattform einen Touch Verspieltheit. Da es funktioniert und nicht stört, sehe ich hier allerdings keinen Handlungsbedarf.

So lets keep it and close this issue?

**Comment by oas777** [comment]
I guess... @dagraf?

**Comment by dagraf** [comment]
I guess so, too.
