### ISSUE TITLE
Embedded videos with timestamp only play audio

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#948]
When opening an `~embed` route with a timestamp, the video doesn't load correctly. It can be played, but doesn't actually show am image, just a grey screen. The audio however plays. Opening the video as picture-in-picture correctly displays the video.

**Comment by owi92** [comment]
Since this apparently isn't reproducible in our deployment, should this be closed? We can always open another issue if it happens again for some reason.

**Comment by LukasKalbertodt** [comment]
Yeah sure, let's close.
