### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#950]
My first critical error

![grafik](https://github.com/elan-ev/tobira/assets/1752342/d2399bfa-77e6-4a0a-9d63-ad6e015b6184)

occured at https://tobira.opencast.org/lectures/d-infk/2019/autumn.

**Comment by owi92** [comment]
Yup this is the bug I was talking about at the beginning of our meeting. Should be fixed with #949

**Comment by LukasKalbertodt** [comment]
This is indeed fixed now.

**Comment by LukasKalbertodt** [comment]
Though ... Ole maybe we should add a playwright test for this. Just making sure pages like this don't crash.

**Comment by owi92** [comment]
Sure, that's a good idea.
