### ISSUE TITLE
Implement some way to add users in the ACL selector

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#951]
Currently we have a bunch of dummy users you can select. That obviously has to be replaced, but with what? The main problem, as described in #671 is that we don't just have a list of all users. And we can't require our login system to provide that. Further, it is even questionable from a privacy standpoint whether that's ok (though for the ETH it would be fine).

A few ideas:

- Tobira can just remember all users that ever logged into Tobira and make that searchable in the UI.
- We can have an import command, e.g. `tobira import-known-users` or something like that where organizations can ingest such a list. That's mostly useful for the beginning period where very few users already logged into Tobira. But it could also be used in a cronjob to push up to date user info.

Regarding privacy one could make it so that users have to enter an exact username instead.

**Comment by oas777** [comment]
Not sure I understand this or whether I'm supposed to comment, but isn't this a general problem many university systems face, like Moodle not knowing (new) students until they logged in? Maybe there's a way these systems work with this so that we can learn from them. Ignore this if I'm on the wrong track.

**Comment by LukasKalbertodt** [comment]
Yes you are right, often in these contexts with a central user management system, applications have this problem. So far I haven't seen a clever solution to this in similar apps. Not to be narrow minded, but I don't think there is not a lot of opportunity to have clever ideas about this. This is a fairly straight forward problem. But I could be missing something of course.
