### ISSUE TITLE
Update caption logic in Opencast module

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#960]
How Opencast does subtitles changed some time ago. Now tracks are used instead of attachments, for example. But there are a few other changes I think. https://github.com/opencast/opencast/issues/4407

I coded the subtitle detection fairly generally back then, and it finds attachments and tracks. So the subtitles are still found. However, subtitle tracks are also sent within the `tracks` array in the harvest response. That is then stored in the Tobira DB, sent out via the GraphQL API and then passed to Paella, which ultimately chokes on it, just showing an error (fair). We should thus filter out subtitle tracks inside the harvest API.

But apart from fixing that specific bug, the whole logic inside the Opencast module should be checked again and tested with the new system to make sure everything works.

**Comment by oas777** [comment]
Probably a bit early to mention this, but if you're messing around with subtitles make sure they also become available for time-based search results together with content from slides.
