### ISSUE TITLE
How do we want to handle loading?

### ISSUE THREAD

**Issue by JulianKniephoff** [elan-ev/tobira#99]
There will often be situations where the frontend has to wait for things like API requests. We should probably come up with some kind of general guidelines about how to handle this in the code, in the design, etc.

**Comment by LukasKalbertodt** [comment]
I have read up on new relay and react APIs. We probably at one point want to use the "render as you fetch" approach which works with "concurrent render mode" in React. Most of the APIs are still not stable, but they have been in development for quite some time and are used in production by Facebook for some time. 

A few key ideas:
- Use `Suspense`: this component renders a callback if any of its children "suspends". 
- Split the current `useLazyLoadQuery` into two operations: `useQueryLoader` and `usePreloadedQuery`. The former sends the GraphQL request, returns a reference to that "in flight request", not the data itself. The other function can be used to actually wait for the data. Crucially, `useQueryLoader` must not be called in rendering code. This makes sure that we don't need to start rendering before fetching data. 
- Use `useTransition` to make loading new pages potentially nicer

The fact that `useQueryLoader` cannot be called in rendering code has a few consequences. Looking at [this example project](https://github.com/relayjs/relay-examples/tree/master/issue-tracker) shows that they use custom router logic to call `useQueryLoader` very early. This would mean some refactoring for us. 

Lastly, there is also the question where the queries even are. Most of the components just want to use fragments. Ideally per route, there should be only one query in total, so the query has to happen high up in the tree. Here too, a custom routing logic would help.

In any case. We decided not to do that now. Waiting has several advantages, e.g. that the APIs get stabilized.

**Comment by LukasKalbertodt** [comment]
We changed our routing logic in #224 to be able to use the new relay functions. That PR also uses those functions and updates to React 18 alpha, using `useTransition` for non-initial page loads. I think it already looks pretty nice. Two main things still have to be done:

- Initial load currently still flashes a "loading (TODO)" before showing any real UI.
- There is no loading indicator at all for the non-initial page loads. It looks good if it loads within a couple 100 ms. But we certainly want a loading indicator. Maybe like on GitHub where there is a loading bar at the very top of the page?
