### ISSUE TITLE
Videos are missing fullscreen and volume buttons on iPhones

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#990]
...which makes the ~~small~~ tiny video/player extra unfortunate. Tested with chrome and safari.
<img width="714" alt="Bildschirmfoto 2023-11-09 um 15 58 00" src="https://github.com/elan-ev/tobira/assets/94838646/a9924b7e-783c-4ec3-957c-7d3f3273be3e">

**Comment by owi92** [comment]
This doesn't appear to be an issue with our integration as it also happens with the opencast and stock paella players. I have opened an issue: https://github.com/polimediaupv/paella-core/issues/346.

**Comment by oas777** [comment]
Won't fix?
